/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.siac.siacbilser.frontend.webservice;

import javax.jws.WebService;

import it.csi.siac.siacbilser.business.service.base.BaseServiceExecutor;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.RicercaAccantonamentoFondiDubbiaEsigibilitaService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.attributibilancio.ImpostaDefaultAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.attributibilancio.ModificaStatoAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.attributibilancio.RicercaDettaglioAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.attributibilancio.RicercaPuntualeAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.attributibilancio.RicercaSinteticaAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.attributibilancio.SalvaAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.attributibilancio.report.excel.AccantonamentoFondiDubbiaEsigibilitaAttributiBilancioExcelReportService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.gestione.AggiornaAccantonamentoFondiDubbiaEsigibilitaGestioneService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.gestione.EliminaAccantonamentoFondiDubbiaEsigibilitaGestioneService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.gestione.InserisceAccantonamentoFondiDubbiaEsigibilitaGestioneService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.gestione.InserisceAccantonamentoFondiDubbiaEsigibilitaImportGestioneService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.gestione.RipristinaAccantonamentoFondiDubbiaEsigibilitaGestioneService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.gestione.SimulaInserisceAccantonamentoFondiDubbiaEsigibilitaImportGestioneService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.previsione.AggiornaAccantonamentoFondiDubbiaEsigibilitaService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.previsione.EliminaAccantonamentoFondiDubbiaEsigibilitaService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.previsione.InserisceAccantonamentoFondiDubbiaEsigibilitaImportService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.previsione.InserisceAccantonamentoFondiDubbiaEsigibilitaService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.previsione.RipristinaAccantonamentoFondiDubbiaEsigibilitaService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.previsione.SimulaInserisceAccantonamentoFondiDubbiaEsigibilitaImportService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.rendiconto.AggiornaAccantonamentoFondiDubbiaEsigibilitaRendicontoService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.rendiconto.CalcolaImportiPerAllegatoArconetService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.rendiconto.EliminaAccantonamentoFondiDubbiaEsigibilitaRendicontoService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.rendiconto.InserisceAccantonamentoFondiDubbiaEsigibilitaImportRendicontoService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.rendiconto.InserisceAccantonamentoFondiDubbiaEsigibilitaRendicontoService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.rendiconto.RipristinaAccantonamentoFondiDubbiaEsigibilitaRendicontoService;
import it.csi.siac.siacbilser.business.service.fondidubbiaesigibilita.rendiconto.SimulaInserisceAccantonamentoFondiDubbiaEsigibilitaImportRendicontoService;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.RicercaAccantonamentoFondiDubbiaEsigibilita;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.RicercaAccantonamentoFondiDubbiaEsigibilitaResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.attributibilancio.AccantonamentoFondiDubbiaEsigibilitaAttributiBilancioExcelReport;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.attributibilancio.AccantonamentoFondiDubbiaEsigibilitaAttributiBilancioExcelReportResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.attributibilancio.ImpostaDefaultAccantonamentoFondiDubbiaEsigibilitaAttributiBilancio;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.attributibilancio.ImpostaDefaultAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.attributibilancio.ModificaStatoAccantonamentoFondiDubbiaEsigibilitaAttributiBilancio;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.attributibilancio.ModificaStatoAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.attributibilancio.RicercaDettaglioAccantonamentoFondiDubbiaEsigibilitaAttributiBilancio;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.attributibilancio.RicercaDettaglioAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.attributibilancio.RicercaPuntualeAccantonamentoFondiDubbiaEsigibilitaAttributiBilancio;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.attributibilancio.RicercaPuntualeAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.attributibilancio.RicercaSinteticaAccantonamentoFondiDubbiaEsigibilitaAttributiBilancio;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.attributibilancio.RicercaSinteticaAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.attributibilancio.SalvaAccantonamentoFondiDubbiaEsigibilitaAttributiBilancio;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.attributibilancio.SalvaAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.gestione.AggiornaAccantonamentoFondiDubbiaEsigibilitaGestione;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.gestione.AggiornaAccantonamentoFondiDubbiaEsigibilitaGestioneResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.gestione.EliminaAccantonamentoFondiDubbiaEsigibilitaGestione;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.gestione.EliminaAccantonamentoFondiDubbiaEsigibilitaGestioneResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.gestione.InserisceAccantonamentoFondiDubbiaEsigibilitaGestione;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.gestione.InserisceAccantonamentoFondiDubbiaEsigibilitaGestioneResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.gestione.InserisceAccantonamentoFondiDubbiaEsigibilitaImportGestione;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.gestione.InserisceAccantonamentoFondiDubbiaEsigibilitaImportGestioneResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.gestione.RipristinaAccantonamentoFondiDubbiaEsigibilitaGestione;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.gestione.RipristinaAccantonamentoFondiDubbiaEsigibilitaGestioneResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.gestione.SimulaInserisceAccantonamentoFondiDubbiaEsigibilitaImportGestione;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.gestione.SimulaInserisceAccantonamentoFondiDubbiaEsigibilitaImportGestioneResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.previsione.AggiornaAccantonamentoFondiDubbiaEsigibilita;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.previsione.AggiornaAccantonamentoFondiDubbiaEsigibilitaResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.previsione.EliminaAccantonamentoFondiDubbiaEsigibilita;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.previsione.EliminaAccantonamentoFondiDubbiaEsigibilitaResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.previsione.InserisceAccantonamentoFondiDubbiaEsigibilita;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.previsione.InserisceAccantonamentoFondiDubbiaEsigibilitaImport;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.previsione.InserisceAccantonamentoFondiDubbiaEsigibilitaImportResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.previsione.InserisceAccantonamentoFondiDubbiaEsigibilitaResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.previsione.RipristinaAccantonamentoFondiDubbiaEsigibilita;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.previsione.RipristinaAccantonamentoFondiDubbiaEsigibilitaResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.previsione.SimulaInserisceAccantonamentoFondiDubbiaEsigibilitaImport;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.previsione.SimulaInserisceAccantonamentoFondiDubbiaEsigibilitaImportResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.rendiconto.AggiornaAccantonamentoFondiDubbiaEsigibilitaRendiconto;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.rendiconto.AggiornaAccantonamentoFondiDubbiaEsigibilitaRendicontoResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.rendiconto.CalcolaImportiPerAllegatoArconet;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.rendiconto.CalcolaImportiPerAllegatoArconetResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.rendiconto.EliminaAccantonamentoFondiDubbiaEsigibilitaRendiconto;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.rendiconto.EliminaAccantonamentoFondiDubbiaEsigibilitaRendicontoResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.rendiconto.InserisceAccantonamentoFondiDubbiaEsigibilitaImportRendiconto;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.rendiconto.InserisceAccantonamentoFondiDubbiaEsigibilitaImportRendicontoResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.rendiconto.InserisceAccantonamentoFondiDubbiaEsigibilitaRendiconto;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.rendiconto.InserisceAccantonamentoFondiDubbiaEsigibilitaRendicontoResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.rendiconto.RipristinaAccantonamentoFondiDubbiaEsigibilitaRendiconto;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.rendiconto.RipristinaAccantonamentoFondiDubbiaEsigibilitaRendicontoResponse;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.rendiconto.SimulaInserisceAccantonamentoFondiDubbiaEsigibilitaImportRendiconto;
import it.csi.siac.siacbilser.frontend.webservice.msg.fcde.rendiconto.SimulaInserisceAccantonamentoFondiDubbiaEsigibilitaImportRendicontoResponse;
import it.csi.siac.siaccommonser.webservice.BaseWebServiceImpl;

/**
 * Implementazione del servizio FondiDubbiaEsigibilitaService.
 *
 * @author Alessandro Marchino
 */
@WebService(serviceName = "FondiDubbiaEsigibilitaService",
portName = "FondiDubbiaEsigibilitaServicePort",
targetNamespace = BILSvcDictionary.NAMESPACE,
endpointInterface = "it.csi.siac.siacbilser.frontend.webservice.FondiDubbiaEsigibilitaService")
public class FondiDubbiaEsigibilitaServiceImpl extends BaseWebServiceImpl implements FondiDubbiaEsigibilitaService {

	// Attributi Bilancio
	@Override
	public ImpostaDefaultAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioResponse initDefaultDettaglioAccantonamentoFondiDubbiaEsigibilitaAttributiBilancio(ImpostaDefaultAccantonamentoFondiDubbiaEsigibilitaAttributiBilancio parameters) {
		return BaseServiceExecutor.execute(appCtx, ImpostaDefaultAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioService.class, parameters);
	}
	@Override
	public RicercaDettaglioAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioResponse ricercaDettaglioAccantonamentoFondiDubbiaEsigibilitaAttributiBilancio(RicercaDettaglioAccantonamentoFondiDubbiaEsigibilitaAttributiBilancio parameters) {
		return BaseServiceExecutor.execute(appCtx, RicercaDettaglioAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioService.class, parameters);
	}
	@Override
	public RicercaPuntualeAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioResponse ricercaPuntualeAccantonamentoFondiDubbiaEsigibilitaAttributiBilancio(RicercaPuntualeAccantonamentoFondiDubbiaEsigibilitaAttributiBilancio parameters) {
		return BaseServiceExecutor.execute(appCtx, RicercaPuntualeAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioService.class, parameters);
	}
	@Override
	public RicercaSinteticaAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioResponse ricercaSinteticaAccantonamentoFondiDubbiaEsigibilitaAttributiBilancio(RicercaSinteticaAccantonamentoFondiDubbiaEsigibilitaAttributiBilancio parameters) {
		return BaseServiceExecutor.execute(appCtx, RicercaSinteticaAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioService.class, parameters);
	}
	@Override
	public SalvaAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioResponse salvaAccantonamentoFondiDubbiaEsigibilitaAttributiBilancio(SalvaAccantonamentoFondiDubbiaEsigibilitaAttributiBilancio parameters) {
		return BaseServiceExecutor.execute(appCtx, SalvaAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioService.class, parameters);
	}
	@Override
	public ModificaStatoAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioResponse modificaStatoAccantonamentoFondiDubbiaEsigibilitaAttributiBilancio(ModificaStatoAccantonamentoFondiDubbiaEsigibilitaAttributiBilancio parameters) {
		return BaseServiceExecutor.execute(appCtx, ModificaStatoAccantonamentoFondiDubbiaEsigibilitaAttributiBilancioService.class, parameters);
	}
	@Override
	public AccantonamentoFondiDubbiaEsigibilitaAttributiBilancioExcelReportResponse accantonamentoFondiDubbiaEsigibilitaAttributiBilancioExcelReport(AccantonamentoFondiDubbiaEsigibilitaAttributiBilancioExcelReport parameters) {
		return BaseServiceExecutor.execute(appCtx, AccantonamentoFondiDubbiaEsigibilitaAttributiBilancioExcelReportService.class, parameters);
	}
	
	// FCDE
	// Ricerca
	@Override
	public RicercaAccantonamentoFondiDubbiaEsigibilitaResponse ricercaAccantonamentoFondiDubbiaEsigibilita(RicercaAccantonamentoFondiDubbiaEsigibilita parameters) {
		return BaseServiceExecutor.execute(appCtx, RicercaAccantonamentoFondiDubbiaEsigibilitaService.class, parameters);
	}
	// Previsione
	@Override
	public InserisceAccantonamentoFondiDubbiaEsigibilitaResponse inserisceAccantonamentoFondiDubbiaEsigibilita(InserisceAccantonamentoFondiDubbiaEsigibilita parameters) {
		return BaseServiceExecutor.execute(appCtx, InserisceAccantonamentoFondiDubbiaEsigibilitaService.class, parameters);
	}
	@Override
	public InserisceAccantonamentoFondiDubbiaEsigibilitaImportResponse inserisceAccantonamentoFondiDubbiaEsigibilitaImport(InserisceAccantonamentoFondiDubbiaEsigibilitaImport parameters) {
		return BaseServiceExecutor.execute(appCtx, InserisceAccantonamentoFondiDubbiaEsigibilitaImportService.class, parameters);
	}
	@Override
	public RipristinaAccantonamentoFondiDubbiaEsigibilitaResponse ripristinaAccantonamentoFondiDubbiaEsigibilita(RipristinaAccantonamentoFondiDubbiaEsigibilita parameters) {
		return BaseServiceExecutor.execute(appCtx, RipristinaAccantonamentoFondiDubbiaEsigibilitaService.class, parameters);
	}
	@Override
	public EliminaAccantonamentoFondiDubbiaEsigibilitaResponse eliminaAccantonamentoFondiDubbiaEsigibilita(EliminaAccantonamentoFondiDubbiaEsigibilita parameters) {
		return BaseServiceExecutor.execute(appCtx, EliminaAccantonamentoFondiDubbiaEsigibilitaService.class, parameters);
	}
	@Override
	public AggiornaAccantonamentoFondiDubbiaEsigibilitaResponse aggiornaAccantonamentoFondiDubbiaEsigibilita(AggiornaAccantonamentoFondiDubbiaEsigibilita parameters) {
		return BaseServiceExecutor.execute(appCtx, AggiornaAccantonamentoFondiDubbiaEsigibilitaService.class, parameters);
	}
	@Override
	public SimulaInserisceAccantonamentoFondiDubbiaEsigibilitaImportResponse simulaInserisceAccantonamentoFondiDubbiaEsigibilitaImport(SimulaInserisceAccantonamentoFondiDubbiaEsigibilitaImport parameters) {
		return BaseServiceExecutor.execute(appCtx, SimulaInserisceAccantonamentoFondiDubbiaEsigibilitaImportService.class, parameters);
	}
	
	// Rendiconto
	@Override
	public InserisceAccantonamentoFondiDubbiaEsigibilitaRendicontoResponse inserisceAccantonamentoFondiDubbiaEsigibilitaRendiconto(InserisceAccantonamentoFondiDubbiaEsigibilitaRendiconto parameters) {
		return BaseServiceExecutor.execute(appCtx, InserisceAccantonamentoFondiDubbiaEsigibilitaRendicontoService.class, parameters);
	}
	@Override
	public InserisceAccantonamentoFondiDubbiaEsigibilitaImportRendicontoResponse inserisceAccantonamentoFondiDubbiaEsigibilitaImportRendiconto(InserisceAccantonamentoFondiDubbiaEsigibilitaImportRendiconto parameters) {
		return BaseServiceExecutor.execute(appCtx, InserisceAccantonamentoFondiDubbiaEsigibilitaImportRendicontoService.class, parameters);
	}
	@Override
	public RipristinaAccantonamentoFondiDubbiaEsigibilitaRendicontoResponse ripristinaAccantonamentoFondiDubbiaRendicontoEsigibilita(RipristinaAccantonamentoFondiDubbiaEsigibilitaRendiconto parameters) {
		return BaseServiceExecutor.execute(appCtx, RipristinaAccantonamentoFondiDubbiaEsigibilitaRendicontoService.class, parameters);
	}
	@Override
	public EliminaAccantonamentoFondiDubbiaEsigibilitaRendicontoResponse eliminaAccantonamentoFondiDubbiaEsigibilitaRendiconto(EliminaAccantonamentoFondiDubbiaEsigibilitaRendiconto parameters) {
		return BaseServiceExecutor.execute(appCtx, EliminaAccantonamentoFondiDubbiaEsigibilitaRendicontoService.class, parameters);
	}
	@Override
	public AggiornaAccantonamentoFondiDubbiaEsigibilitaRendicontoResponse aggiornaAccantonamentoFondiDubbiaEsigibilitaRendiconto(AggiornaAccantonamentoFondiDubbiaEsigibilitaRendiconto parameters) {
		return BaseServiceExecutor.execute(appCtx, AggiornaAccantonamentoFondiDubbiaEsigibilitaRendicontoService.class, parameters);
	}
	@Override
	public SimulaInserisceAccantonamentoFondiDubbiaEsigibilitaImportRendicontoResponse simulaInserisceAccantonamentoFondiDubbiaEsigibilitaImportRendiconto(SimulaInserisceAccantonamentoFondiDubbiaEsigibilitaImportRendiconto parameters) {
		return BaseServiceExecutor.execute(appCtx, SimulaInserisceAccantonamentoFondiDubbiaEsigibilitaImportRendicontoService.class, parameters);
	}

	// Gestione
	@Override
	public InserisceAccantonamentoFondiDubbiaEsigibilitaGestioneResponse inserisceAccantonamentoFondiDubbiaEsigibilitaGestione(InserisceAccantonamentoFondiDubbiaEsigibilitaGestione parameters) {
		return BaseServiceExecutor.execute(appCtx, InserisceAccantonamentoFondiDubbiaEsigibilitaGestioneService.class, parameters);
	}
	@Override
	public InserisceAccantonamentoFondiDubbiaEsigibilitaImportGestioneResponse inserisceAccantonamentoFondiDubbiaEsigibilitaImportGestione(InserisceAccantonamentoFondiDubbiaEsigibilitaImportGestione parameters) {
		return BaseServiceExecutor.execute(appCtx, InserisceAccantonamentoFondiDubbiaEsigibilitaImportGestioneService.class, parameters);
	}
	@Override
	public RipristinaAccantonamentoFondiDubbiaEsigibilitaGestioneResponse ripristinaAccantonamentoFondiDubbiaGestioneEsigibilita(RipristinaAccantonamentoFondiDubbiaEsigibilitaGestione parameters) {
		return BaseServiceExecutor.execute(appCtx, RipristinaAccantonamentoFondiDubbiaEsigibilitaGestioneService.class, parameters);
	}
	@Override
	public EliminaAccantonamentoFondiDubbiaEsigibilitaGestioneResponse eliminaAccantonamentoFondiDubbiaEsigibilitaGestione(EliminaAccantonamentoFondiDubbiaEsigibilitaGestione parameters) {
		return BaseServiceExecutor.execute(appCtx, EliminaAccantonamentoFondiDubbiaEsigibilitaGestioneService.class, parameters);
	}
	@Override
	public AggiornaAccantonamentoFondiDubbiaEsigibilitaGestioneResponse aggiornaAccantonamentoFondiDubbiaEsigibilitaGestione(AggiornaAccantonamentoFondiDubbiaEsigibilitaGestione parameters) {
		return BaseServiceExecutor.execute(appCtx, AggiornaAccantonamentoFondiDubbiaEsigibilitaGestioneService.class, parameters);
	}
	@Override
	public SimulaInserisceAccantonamentoFondiDubbiaEsigibilitaImportGestioneResponse simulaInserisceAccantonamentoFondiDubbiaEsigibilitaImportGestione(SimulaInserisceAccantonamentoFondiDubbiaEsigibilitaImportGestione parameters) {
		return BaseServiceExecutor.execute(appCtx, SimulaInserisceAccantonamentoFondiDubbiaEsigibilitaImportGestioneService.class, parameters);
	}

	// Allegato C
	@Override
	public CalcolaImportiPerAllegatoArconetResponse calcolaCampiAllegatoArconet(CalcolaImportiPerAllegatoArconet parameters) {
		return BaseServiceExecutor.execute(appCtx, CalcolaImportiPerAllegatoArconetService.class, parameters);
	}
}
