/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.siac.siacbilser.integration.entitymapping.converter.base;

import java.util.EnumSet;
import java.util.Set;

import org.dozer.CustomConverter;
import org.dozer.DozerConverter;

import it.csi.siac.siacattser.model.AttoAmministrativoModelDetail;
import it.csi.siac.siacbilser.business.utility.Utility;
import it.csi.siac.siacbilser.integration.entitymapping.converter.*;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.AmmortamentoAnnuoCespiteCespiteConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.AmmortamentoAnnuoCespiteDettaglioAmmortamentoAnnuoCespiteAnnoSpecificoConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.AmmortamentoAnnuoCespiteDettaglioAmmortamentoAnnuoCespiteConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.AmmortamentoAnnuoCespiteDettaglioAmmortamentoAnnuoCespiteModelDetailConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.CategoriaCespitiAliquotaAnnuaConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.CategoriaCespitiAnnullatoConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.CategoriaCespitiTipoCalcoloConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.CespiteAmmortamentoAnnuoCespiteModelDetailConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.CespiteClassificazioneGiuridicaConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.CespiteDismissioneCespiteConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.CespiteFondoAmmortamentoConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.CespiteImportoSuRegistroAConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.CespiteIsCollegatoAPrimeNoteConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.CespiteIsInserimentoContestualeRegistroAConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.CespiteTipoBeneCespiteConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.CespiteTipoBeneCespiteModelDetailConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.DettaglioAmmortamentoAnnuoCespiteAmmortamentoAnnuoCespiteConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.DettaglioAmmortamentoAnnuoCespiteAmmortamentoAnnuoCespiteModelDetailConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.DettaglioAmmortamentoAnnuoCespitePrimaNotaConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.DettaglioAmmortamentoAnnuoCespitePrimaNotaModelDetailConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.DettaglioAnteprimaAmmortamentoAnnuoCespiteAnteprimaConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.DettaglioAnteprimaAmmortamentoAnnuoCespiteContoConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.DettaglioAnteprimaAmmortamentoAnnuoCespiteSegnoConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.DismissioneCespiteAttoAmmConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.DismissioneCespiteCausaleEPConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.DismissioneCespiteEventoConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.DismissioneCespiteNumeroCespitiCollegatiConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.DismissioneCespiteStatoDismissioneCespiteConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.TipoBeneCespiteCategoriaCespitiConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.TipoBeneCespiteCategoriaCespitiModelDetailConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.TipoBeneCespiteCausaleEPAmmortamentoConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.TipoBeneCespiteCausaleEPDecrementoConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.TipoBeneCespiteCausaleEPIncrementoConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.TipoBeneCespiteContoAlienazioneConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.TipoBeneCespiteContoAmmortamentoConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.TipoBeneCespiteContoDecrementoConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.TipoBeneCespiteContoDonazioneConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.TipoBeneCespiteContoFondoAmmortamentoConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.TipoBeneCespiteContoIncrementoConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.TipoBeneCespiteContoMinusvalenzaConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.TipoBeneCespiteContoPatrimonialeConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.TipoBeneCespiteContoPlusvalenzaConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.TipoBeneCespiteEventoAmmortamentoConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.TipoBeneCespiteEventoDecrementoConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.TipoBeneCespiteEventoIncrementoConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.TipoBeneCespiteFlagAnnullatoConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.VariazioneCespiteCespiteConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.VariazioneCespiteCespiteModelDetailConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.cespiti.VariazioneCespiteStatoVariazioneCespiteConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.componenteimporticapitolo.ComponenteImportiCapitoloHasVariazioniConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.componenteimporticapitolo.ComponenteImportiCapitoloImportiCapitoloConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.componenteimporticapitolo.ComponenteImportiCapitoloImportoConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.componenteimporticapitolo.ComponenteImportiCapitoloTipoComponenteImportiCapitoloConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.componenteimporticapitolo.DettaglioVariazioneComponenteImportoCapitoloComponenteImportiCapitoloConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.componenteimporticapitolo.DettaglioVariazioneComponenteImportoCapitoloDettaglioVariazioneImportiCapitoloConverter;
import it.csi.siac.siacbilser.integration.entitymapping.converter.componenteimporticapitolo.DettaglioVariazioneComponenteImportoCapitoloFlagConverter;
import it.csi.siac.siacbilser.model.AccantonamentoFondiDubbiaEsigibilitaModelDetail;
import it.csi.siac.siacbilser.model.AccantonamentoFondiDubbiaEsigibilitaRendicontoModelDetail;
import it.csi.siac.siacbilser.model.ComponenteImportiCapitoloModelDetail;
import it.csi.siac.siacbilser.model.DettaglioVariazioneComponenteImportoCapitoloModelDetail;
import it.csi.siac.siacbilser.model.ModelDetail;
import it.csi.siac.siacbilser.model.QuadroEconomicoModelDetail;
import it.csi.siac.siacbilser.model.VariazioneImportoCapitoloModelDetail;
import it.csi.siac.siaccecser.model.RichiestaEconomaleModelDetail;
import it.csi.siac.siaccecser.model.StampeCassaFileModelDetail;
import it.csi.siac.siaccespser.model.AmmortamentoAnnuoCespiteModelDetail;
import it.csi.siac.siaccespser.model.CategoriaCespitiModelDetail;
import it.csi.siac.siaccespser.model.CespiteModelDetail;
import it.csi.siac.siaccespser.model.DettaglioAmmortamentoAnnuoCespiteModelDetail;
import it.csi.siac.siaccespser.model.DettaglioAnteprimaAmmortamentoAnnuoCespiteModelDetail;
import it.csi.siac.siaccespser.model.DismissioneCespiteModelDetail;
import it.csi.siac.siaccespser.model.TipoBeneCespiteModelDetail;
import it.csi.siac.siaccespser.model.VariazioneCespiteModelDetail;
import it.csi.siac.siacfin2ser.model.AccertamentoModelDetail;
import it.csi.siac.siacfin2ser.model.AllegatoAttoModelDetail;
import it.csi.siac.siacfin2ser.model.CapitoloEntrataGestioneModelDetail;
import it.csi.siac.siacfin2ser.model.CapitoloEntrataPrevisioneModelDetail;
import it.csi.siac.siacfin2ser.model.CapitoloModelDetail;
import it.csi.siac.siacfin2ser.model.CapitoloUscitaGestioneModelDetail;
import it.csi.siac.siacfin2ser.model.CapitoloUscitaPrevisioneModelDetail;
import it.csi.siac.siacfin2ser.model.DocumentoEntrataModelDetail;
import it.csi.siac.siacfin2ser.model.DocumentoSpesaModelDetail;
import it.csi.siac.siacfin2ser.model.ElencoDocumentiAllegatoModelDetail;
import it.csi.siac.siacfin2ser.model.ImpegnoModelDetail;
import it.csi.siac.siacfin2ser.model.LiquidazioneModelDetail;
import it.csi.siac.siacfin2ser.model.PreDocumentoEntrataModelDetail;
import it.csi.siac.siacfin2ser.model.PreDocumentoSpesaModelDetail;
import it.csi.siac.siacfin2ser.model.SubAccertamentoModelDetail;
import it.csi.siac.siacfin2ser.model.SubImpegnoModelDetail;
import it.csi.siac.siacfin2ser.model.SubdocumentoEntrataModelDetail;
import it.csi.siac.siacfin2ser.model.SubdocumentoIvaModelDetail;
import it.csi.siac.siacfin2ser.model.SubdocumentoSpesaModelDetail;
import it.csi.siac.siacfin2ser.model.TipoComponenteImportiCapitoloModelDetail;
import it.csi.siac.siacfin2ser.model.TipoOnereModelDetail;
import it.csi.siac.siacgenser.model.CausaleEPModelDetail;
import it.csi.siac.siacgenser.model.ClassificatoreGSAModelDetail;
import it.csi.siac.siacgenser.model.ContoModelDetail;
import it.csi.siac.siacgenser.model.MovimentoDettaglioModelDetail;
import it.csi.siac.siacgenser.model.MovimentoEPModelDetail;
import it.csi.siac.siacgenser.model.PrimaNotaModelDetail;
import it.csi.siac.siacgenser.model.ProgettoModelDetail;
import it.csi.siac.siacgenser.model.RegistrazioneMovFinModelDetail;

/**
 * Mapping tra i ModelDetail e i Converter di Dozer.
 * Permette di ottenere il converter associato ad un ModelDetail.
 * 
 * 
 * @author Domenico
 *
 */

//#### Tips per popolare in "automatico" questo enum:
//## Copiarsi la lista dei converter con estensione .java uno per riga. Effettuare il seguente replace:
//## Find:         SubdocumentoSpesa(.*)Converter\.java
//## Replace With: SubdocumentoSpesa$1\(SubdocumentoSpesa$1Converter\.class, SubdocumentoSpesaModelDetail\.$1\),

public enum Converters implements Converter   {
	
	AllegatoAttoDataInizioValiditaStato (AllegatoAttoDataInizioValiditaStatoConverter.class, AllegatoAttoModelDetail.DataInizioValiditaStato),
	AllegatoAttoDatiSoggetto(AllegatoAttoDatiSoggettoConverter.class, AllegatoAttoModelDetail.DatiSoggetto),
	AllegatoAttoElencoDocumenti(AllegatoAttoElencoDocumentiConverter.class, AllegatoAttoModelDetail.ElencoDocumenti),
	AllegatoAttoElencoDocumentiModelDetail(AllegatoAttoElencoDocumentiModelDetailConverter.class, AllegatoAttoModelDetail.ElencoDocumentiModelDetail),
	
	// SIAC-5021
	AllegatoAttoIsAssociatoAdAlmenoUnaQuotaSpesa(AllegatoAttoIsAssociatoAdAlmenoUnaQuotaSpesaConverter.class, AllegatoAttoModelDetail.IsAssociatoAdAlmenoUnaQuotaSpesa),
	AllegatoAttoIsAssociatoAdUnDocumento(AllegatoAttoIsAssociatoAdUnDocumentoConverter.class, AllegatoAttoModelDetail.IsAssociatoAdUnDocumento),
	AllegatoAttoIsAssociatoAdUnSubdocumentoSospeso(AllegatoAttoIsAssociatoAdUnSubdocumentoSospesoConverter.class, AllegatoAttoModelDetail.IsAssociatoAdUnSubdocumentoSospeso),
	AllegatoAttoElencoDocumentiConPagatoIncassato(AllegatoAttoElencoDocumentiConPagatoIncassatoConverter.class, AllegatoAttoModelDetail.ElencoDocumentiConPagatoIncassato),
	AllegatoAttoDataCompletamento(AllegatoAttoDataCompletamentoConverter.class, AllegatoAttoModelDetail.DataCompletamento),
	AllegatoAttoIsAssociatoAdUnSubdocumentoConOrdinativo(AllegatoAttoIsAssociatoAdUnSubdocumentoConOrdinativoConverter.class, AllegatoAttoModelDetail.IsAssociatoAdUnSubdocumentoConOrdinativo),
	// SIAC-6261
	AllegatoAttoElencoSoggettiDurc(AllegatoAttoElencoSoggettiDurcConverter.class, AllegatoAttoModelDetail.ElencoSoggettiDurc), 
	AllegatoAttoAllegatoHasImpegnoConfermaDataFineValiditaDurc(AllegatoAttoHasImpegnoConfermaDurcDataFineValiditaConverter.class, AllegatoAttoModelDetail.HasImpegnoConfermaDurcDataFineValidita),

	
	
	TipoOnereAttr(TipoOnereAttrConverter.class, TipoOnereModelDetail.Attr),
	TipoOnereCausali(TipoOnereCausaliConverter.class, TipoOnereModelDetail.Causali),
//	tipoOnereCausaliImpegno(TipoOnereCausaliImpegnoConverter.class, TipoOnereModelDetail.CausaliImpegno),
//	tipoOnereCausaliAccertamento(TipoOnereCausaliAccertamentoConverter.class, TipoOnereModelDetail.CausaliAccertamento),

	tipoOnereAttivita(TipoOnereAttivitaConverter.class, TipoOnereModelDetail.Attivita),
	
	//SIAC-6881: CAPITOLI
	CapitoloAttiDiLegge(CapitoloAttiDiLeggeConverter.class, CapitoloModelDetail.AttoDiLegge),
	CapitoloBilancio(CapitoloAttiDiLeggeConverter.class, CapitoloModelDetail.Bilancio),
	CapitoloCategoria(CapitoloCategoriaConverter.class, CapitoloModelDetail.Categoria),
	CapitoloDataAnnullamento(BilElemDataAnnullamentoConverter.class, CapitoloModelDetail.DataAnnullamento),
	CapitoloEnte(CapitoloEnteConverter.class, CapitoloModelDetail.Ente),
	CapitoloExCapitolo(CapitoloExCapitoloConverter.class, CapitoloModelDetail.ExCapitolo),
	CapitoloStato(BilElemStatoConverter.class, CapitoloModelDetail.Stato),
	
	//CAPITOLI ENTRATA GESTIONE
	CapitoloEntrataGestioneAttiDiLegge(CapitoloAttiDiLeggeConverter.class, CapitoloEntrataGestioneModelDetail.AttoDiLegge),
	CapitoloEntrataGestioneAttributi(CapitoloEntrataGestioneAttrConverter.class, CapitoloEntrataGestioneModelDetail.Attributi),
	CapitoloEntrataGestioneBilancio(CapitoloAttiDiLeggeConverter.class, CapitoloEntrataGestioneModelDetail.Bilancio),
	CapitoloEntrataGestioneCapitoloEquivalente(CapitoloEntrataGestioneCapitoloEquivalenteConverter.class, CapitoloEntrataGestioneModelDetail.CapitoloEquivalente),
	CapitoloEntrataGestioneCategoria(CapitoloCategoriaConverter.class, CapitoloEntrataGestioneModelDetail.Categoria),
	CapitoloEntrataGestioneClassif(NoopConverter.class, CapitoloEntrataGestioneModelDetail.Classificatori),
	CapitoloEntrataGestioneDataAnnullamento(BilElemDataAnnullamentoConverter.class, CapitoloEntrataGestioneModelDetail.DataAnnullamento),
	CapitoloEntrataGestioneEnte(CapitoloEnteConverter.class, CapitoloEntrataGestioneModelDetail.Ente),
	CapitoloEntrataGestioneExCapitolo(CapitoloExCapitoloConverter.class, CapitoloEntrataGestioneModelDetail.ExCapitolo),
	CapitoloEntrataGestioneImporti(NoopConverter.class, CapitoloEntrataGestioneModelDetail.Importi),
	CapitoloEntrataGestioneStato(BilElemStatoConverter.class, CapitoloEntrataGestioneModelDetail.Stato),
	
	//CAPITOLI ENTRATA PREVISIONE
	CapitoloEntrataPrevisioneAttiDiLegge(CapitoloAttiDiLeggeConverter.class, CapitoloEntrataPrevisioneModelDetail.AttoDiLegge),
	CapitoloEntrataPrevisioneAttributi(CapitoloEntrataPrevisioneAttrConverter.class, CapitoloEntrataPrevisioneModelDetail.Attributi),
	CapitoloEntrataPrevisioneBilancio(CapitoloBilancioConverter.class, CapitoloEntrataPrevisioneModelDetail.Bilancio),
	CapitoloEntrataPrevisioneCapitoloEquivalente(CapitoloEntrataPrevisioneCapitoloEquivalenteConverter.class, CapitoloEntrataPrevisioneModelDetail.CapitoloEquivalente),
	CapitoloEntrataPrevisioneCategoria(CapitoloCategoriaConverter.class, CapitoloEntrataPrevisioneModelDetail.Categoria),
	CapitoloEntrataPrevisioneClassif(NoopConverter.class, CapitoloEntrataPrevisioneModelDetail.Classificatori),
	CapitoloEntrataPrevisioneDataAnnullamento(BilElemDataAnnullamentoConverter.class, CapitoloEntrataPrevisioneModelDetail.DataAnnullamento),
	CapitoloEntrataPrevisioneEnte(CapitoloEnteConverter.class, CapitoloEntrataPrevisioneModelDetail.Ente),
	CapitoloEntrataPrevisioneExCapitolo(CapitoloExCapitoloConverter.class, CapitoloEntrataPrevisioneModelDetail.ExCapitolo),
	CapitoloEntrataPrevisioneImporti(NoopConverter.class, CapitoloEntrataPrevisioneModelDetail.Importi),
	CapitoloEntrataPrevisioneStato(BilElemStatoConverter.class, CapitoloEntrataPrevisioneModelDetail.Stato),
	
	//CAPITOLI USCITA GESTIONE
	CapitoloUscitaGestioneAttiDiLegge(CapitoloAttiDiLeggeConverter.class, CapitoloUscitaGestioneModelDetail.AttoDiLegge),
	CapitoloUscitaGestioneAttributi(CapitoloUscitaGestioneAttrConverter.class, CapitoloUscitaGestioneModelDetail.Attributi),
	CapitoloUscitaGestioneBilancio(CapitoloBilancioConverter.class, CapitoloUscitaGestioneModelDetail.Bilancio),
	CapitoloUscitaGestioneCapitoloEquivalente(CapitoloUscitaGestioneCapitoloEquivalenteConverter.class, CapitoloUscitaGestioneModelDetail.CapitoloEquivalente),
	CapitoloUscitaGestioneCategoria(CapitoloCategoriaConverter.class, CapitoloUscitaGestioneModelDetail.Categoria),
	CapitoloUscitaGestioneClassif(NoopConverter.class, CapitoloUscitaGestioneModelDetail.Classificatori),
	CapitoloUscitaGestioneDataAnnullamento(BilElemDataAnnullamentoConverter.class, CapitoloUscitaGestioneModelDetail.DataAnnullamento),
	CapitoloUscitaGestioneEnte(CapitoloEnteConverter.class, CapitoloUscitaGestioneModelDetail.Ente),
	CapitoloUscitaGestioneExCapitolo(CapitoloExCapitoloConverter.class, CapitoloUscitaGestioneModelDetail.ExCapitolo),
	CapitoloUscitaGestioneImporti(NoopConverter.class, CapitoloUscitaGestioneModelDetail.Importi),
	CapitoloUscitaGestioneStato(BilElemStatoConverter.class, CapitoloUscitaGestioneModelDetail.Stato),

	//CAPITOLI USCITA PREVISIONE
	CapitoloUscitaPrevisioneAttiDiLegge(CapitoloAttiDiLeggeConverter.class, CapitoloUscitaPrevisioneModelDetail.AttoDiLegge),
	CapitoloUscitaPrevisioneAttributi(CapitoloUscitaPrevisioneAttrConverter.class, CapitoloUscitaPrevisioneModelDetail.Attributi),
	CapitoloUscitaPrevisioneBilancio(CapitoloBilancioConverter.class, CapitoloUscitaPrevisioneModelDetail.Bilancio),
	CapitoloUscitaPrevisioneCapitoloEquivalente(CapitoloUscitaPrevisioneCapitoloEquivalenteConverter.class, CapitoloUscitaPrevisioneModelDetail.CapitoloEquivalente),
	CapitoloUscitaPrevisioneCategoria(CapitoloCategoriaConverter.class, CapitoloUscitaPrevisioneModelDetail.Categoria),
	CapitoloUscitaPrevisioneClassif(NoopConverter.class, CapitoloUscitaPrevisioneModelDetail.Classificatori),
	CapitoloUscitaPrevisioneDataAnnullamento(BilElemDataAnnullamentoConverter.class, CapitoloUscitaPrevisioneModelDetail.DataAnnullamento),
	CapitoloUscitaPrevisioneEnte(CapitoloEnteConverter.class, CapitoloUscitaPrevisioneModelDetail.Ente),
	CapitoloUscitaPrevisioneExCapitolo(CapitoloExCapitoloConverter.class, CapitoloUscitaPrevisioneModelDetail.ExCapitolo),
	CapitoloUscitaPrevisioneImporti(NoopConverter.class, CapitoloUscitaPrevisioneModelDetail.Importi),
	CapitoloUscitaPrevisioneStato(BilElemStatoConverter.class, CapitoloUscitaPrevisioneModelDetail.Stato),
	
	ContoAttr(ContoAttrConverter.class, ContoModelDetail.Attr),
	ContoCausaliEP(ContoAttrConverter.class, ContoModelDetail.CausaliEP),
	ContoClassif(ContoClassifConverter.class, ContoModelDetail.Classif),
	ContoClassifExtended(ContoClassifExtendedConverter.class, ContoModelDetail.ClassifExtended),
	ContoContoCollegato(ContoContoCollegatoConverter.class, ContoModelDetail.ContoCollegato),
	ContoSoggetto(ContoSoggettoConverter.class, ContoModelDetail.Soggetto),
	ContoTipoConto(ContoTipoContoConverter.class, ContoModelDetail.TipoConto),
	
	CausaleEPStato(CausaleEPStatoConverter.class, CausaleEPModelDetail.Stato),
	CausaleEPConto(CausaleEPContoConverter.class, CausaleEPModelDetail.Conto),
	CausaleEPEvento(CausaleEPEventoConverter.class, CausaleEPModelDetail.Evento),
	CausaleEPSoggetto(CausaleEPSoggettoConverter.class, CausaleEPModelDetail.Soggetto),
	CausaleEPTipo(CausaleEPTipoConverter.class, CausaleEPModelDetail.Tipo),
	CausaleEPMov(CausaleEPMovConverter.class, CausaleEPModelDetail.Mov),
	CausaleEPEnte(CausaleEPEnteConverter.class, CausaleEPModelDetail.Ente),
	CausaleEPClassif(CausaleEPClassifConverter.class, CausaleEPModelDetail.Classif),
//	CausaleEPClasseConciliazione(CausaleEPClasseConciliazioneConverter.class, CausaleEPModelDetail.ClasseConciliazione),
	
	//DocumentoSpesa
	DocumentoSpesaTipoDocumento(DocumentoTipoDocumentoConverter.class, DocumentoSpesaModelDetail.TipoDocumento),
	DocumentoSpesaAttr(DocumentoSpesaAttrConverter.class, DocumentoSpesaModelDetail.Attr),
	DocumentoSpesaSogg(DocumentoSpesaSoggConverter.class, DocumentoSpesaModelDetail.Soggetto),
	DocumentoSpesaClassif(DocumentoSpesaClassifConverter.class, DocumentoSpesaModelDetail.Classif),
	DocumentoSpesaCodicePCC(DocumentoSpesaCodicePCCConverter.class, DocumentoSpesaModelDetail.CodicePCC),
	DocumentoSpesaCodiceUfficioDestinatarioPCC(DocumentoSpesaCodiceUfficioDestinatarioPCCConverter.class, DocumentoSpesaModelDetail.CodiceUfficioDestinatarioPCC),
	DocumentoSpesaCollegatoAdAllegatoAtto(DocumentoSpesaCollegatoAdAllegatoAttoConverter.class, DocumentoSpesaModelDetail.CollegatoAdAllegatoAtto),
	DocumentoSpesaDataInizioValiditaStato(DocumentoSpesaDataInizioValiditaStatoConverter.class, DocumentoSpesaModelDetail.DataInizioValiditaStato),
	DocumentoSpesaDocumentiCollegati(DocumentoSpesaDocumentiCollegatiConverter.class, DocumentoSpesaModelDetail.DocumentiCollegati),
	DocumentoSpesaFatturaFEL(DocumentoSpesaFatturaFELConverter.class, DocumentoSpesaModelDetail.FatturaFEL),
	DocumentoSpesaImportoDaPagareNonPagatoInCassaEconomale(DocumentoSpesaImportoDaPagareNonPagatoInCassaEconomaleConverter.class, DocumentoSpesaModelDetail.ImportoDaPagareNonPagatoInCassaEconomale),
	DocumentoSpesaOnere(DocumentoSpesaOnereConverter.class, DocumentoSpesaModelDetail.Onere),
	DocumentoSpesaOrdini(DocumentoSpesaOrdiniConverter.class, DocumentoSpesaModelDetail.Ordini),
	DocumentoSpesaRegistroComunicazioniPCC(DocumentoSpesaRegistroComunicazioniPCCConverter.class, DocumentoSpesaModelDetail.RegistroComunicazioniPCC),
	DocumentoSpesaRegistroUnico(DocumentoSpesaRegistroUnicoConverter.class, DocumentoSpesaModelDetail.RegistroUnico),
	DocumentoSpesaStato(DocumentoSpesaStatoConverter.class, DocumentoSpesaModelDetail.Stato),
	DocumentoSpesaSubdocumentoIva(DocumentoSpesaSubdocumentoIvaConverter.class, DocumentoSpesaModelDetail.SubdocumentoIva),
	DocumentoSpesaSubdocumentoSpesa(DocumentoSpesaSubdocumentoSpesaConverter.class, DocumentoSpesaModelDetail.SubdocumentoSpesa),
	DocumentoSpesaSiopeDocumentoTipo(DocumentoSpesaSiopeDocumentoTipoConverter.class, DocumentoSpesaModelDetail.SiopeDocumentoTipo),
	DocumentoSpesaSiopeDocumentoTipoAnalogico(DocumentoSpesaSiopeDocumentoTipoAnalogicoConverter.class, DocumentoSpesaModelDetail.SiopeDocumentoTipoAnalogico),
	DocumentoSpesaTotaliImportiQuote(DocumentoTotaliImportiQuoteConverter.class, DocumentoSpesaModelDetail.TotaliImportiQuote),
	DocumentoSpesaTotaleImportoDocumentiEntrataFiglio(DocumentoTotaleImportoDocumentiEntrataFiglioConverter.class, DocumentoSpesaModelDetail.TotaleImportoDocumentiEntrataFiglio),
	DocumentoSpesaTotaleImportoDocumentiSpesaFiglio(DocumentoTotaleImportoDocumentiSpesaFiglioConverter.class, DocumentoSpesaModelDetail.TotaleImportoDocumentiSpesaFiglio),
	DocumentoSpesaTotaliImportiNoteCredito(DocumentoTotaliImportiNoteCreditoConverter.class, DocumentoSpesaModelDetail.TotaliImportiNoteCredito),
	DocumentoSpesaTotaliImportiRilevantiIvaQuote(DocumentoTotaliImportiRilevantiIvaQuoteConverter.class, DocumentoSpesaModelDetail.TotaliImportiRilevantiIvaQuote),
	DocumentoSpesaEsisteQuotaRilevanteIva(DocumentoEsisteQuotaRilevanteIvaConverter.class, DocumentoSpesaModelDetail.EsisteQuotaRilevanteIva),
	DocumentoSpesaEsisteNCDCollegataADocumento(DocumentoEsisteNCDCollegataADocumentoConverter.class, DocumentoSpesaModelDetail.EsisteNCDCollegataADocumento),
	
	//DocumentoEntrata
	DocumentoEtrataTipoDocumento(DocumentoTipoDocumentoConverter.class, DocumentoEntrataModelDetail.TipoDocumento),
	DocumentoEntrataAttr(DocumentoEntrataAttrConverter.class, DocumentoEntrataModelDetail.Attr),
	DocumentoEntrataClassif(DocumentoEntrataClassifConverter.class, DocumentoEntrataModelDetail.Classif),
	DocumentoEntrataDataInizioValiditaStato(DocumentoEntrataDataInizioValiditaStatoConverter.class, DocumentoEntrataModelDetail.DataInizioValiditaStato),
	DocumentoEntrataDocumentiCollegati(DocumentoEntrataDocumentiCollegatiConverter.class, DocumentoEntrataModelDetail.DocumentiCollegati),
	DocumentoEntrataSogg(DocumentoEntrataSoggConverter.class, DocumentoEntrataModelDetail.Sogg),
	DocumentoEntrataStato(DocumentoEntrataStatoConverter.class, DocumentoEntrataModelDetail.Stato),
	DocumentoEntrataSubdocumentoEntrata(DocumentoEntrataSubdocumentoEntrataConverter.class, DocumentoEntrataModelDetail.SubdocumentoEntrata),
	DocumentoEntrataSubdocumentoIva(DocumentoEntrataSubdocumentoIvaConverter.class, DocumentoEntrataModelDetail.SubdocumentoIva),
	DocumentoEntrataTotaliImportiQuote(DocumentoTotaliImportiQuoteConverter.class, DocumentoEntrataModelDetail.TotaliImportiQuote),
	DocumentoEntrataTotaleImportoDocumentiEntrataFiglio(DocumentoTotaleImportoDocumentiEntrataFiglioConverter.class, DocumentoEntrataModelDetail.TotaleImportoDocumentiEntrataFiglio),
	DocumentoEntrataTotaleImportoDocumentiSpesaFiglio(DocumentoTotaleImportoDocumentiSpesaFiglioConverter.class, DocumentoEntrataModelDetail.TotaleImportoDocumentiSpesaFiglio),
	DocumentoEntrataTotaliImportiNoteCredito(DocumentoTotaliImportiNoteCreditoConverter.class, DocumentoEntrataModelDetail.TotaliImportiNoteCredito),
	DocumentoEntrataTotaliImportiRilevantiIvaQuote(DocumentoTotaliImportiRilevantiIvaQuoteConverter.class, DocumentoEntrataModelDetail.TotaliImportiRilevantiIvaQuote),
	DocumentoEntrataEsisteQuotaRilevanteIva(DocumentoEsisteQuotaRilevanteIvaConverter.class, DocumentoEntrataModelDetail.EsisteQuotaRilevanteIva),
	DocumentoEntrataEsisteNCDCollegataADocumento(DocumentoEsisteNCDCollegataADocumentoConverter.class, DocumentoEntrataModelDetail.EsisteNCDCollegataADocumento),
	
	//SubdocumentoSpesa
	SubdocumentoSpesaAttoAmm(SubdocumentoSpesaAttoAmmConverter.class, SubdocumentoSpesaModelDetail.AttoAmm),
	SubdocumentoSpesaAttr(SubdocumentoSpesaAttrConverter.class, SubdocumentoSpesaModelDetail.Attr),
	SubdocumentoSpesaClassif(SubdocumentoSpesaClassifConverter.class, SubdocumentoSpesaModelDetail.Classif),
	SubdocumentoSpesaCommissioniDocumento(SubdocumentoSpesaCommissioniDocumentoConverter.class, SubdocumentoSpesaModelDetail.CommissioniDocumento),
	SubdocumentoSpesaDocPadre(SubdocumentoSpesaDocPadreConverter.class, SubdocumentoSpesaModelDetail.DocPadre),
	SubdocumentoSpesaTestataDocumento(SubdocumentoSpesaTestataDocumentoConverter.class,SubdocumentoSpesaModelDetail.TestataDocumento),
	SubdocumentoSpesaElencoDocumenti(SubdocumentoSpesaElencoDocumentiConverter.class, SubdocumentoSpesaModelDetail.ElencoDocumenti),
	SubdocumentoSpesaHasRitenute(SubdocumentoSpesaHasRitenuteConverter.class, SubdocumentoSpesaModelDetail.HasRitenute),
	SubdocumentoSpesaHasSubordinati(SubdocumentoSpesaHasSubordinatiConverter.class, SubdocumentoSpesaModelDetail.HasSubordinati),
	SubdocumentoSpesaImpegnoSubimpegno(SubdocumentoSpesaImpegnoSubimpegnoConverter.class, SubdocumentoSpesaModelDetail.ImpegnoSubimpegno),
	SubdocumentoSpesaImpegnoSubimpegnoPdc(SubdocumentoSpesaImpegnoSubimpegnoPdcConverter.class, SubdocumentoSpesaModelDetail.ImpegnoSubimpegnoPdc),
	SubdocumentoSpesaImpegnoSubimpegnoConDisponibilita(SubdocumentoSpesaImpegnoSubimpegnoConDisponibilitaConverter.class, SubdocumentoSpesaModelDetail.ImpegnoSubimpegnoConDisponibilita),
	SubdocumentoSpesaIsSubordinato(SubdocumentoSpesaIsSubordinatoConverter.class, SubdocumentoSpesaModelDetail.IsSubordinato),
	SubdocumentoSpesaLiquidazione(SubdocumentoSpesaLiquidazioneConverter.class, SubdocumentoSpesaModelDetail.Liquidazione),
	SubdocumentoSpesaLiquidazioneMinimalStato(SubdocumentoSpesaLiquidazioneMinimalStatoConverter.class, SubdocumentoSpesaModelDetail.LiquidazioneMinimalStato),
	SubdocumentoSpesaModPag(SubdocumentoSpesaModPagConverter.class, SubdocumentoSpesaModelDetail.ModPag),
	SubdocumentoSpesaOrdinativo(SubdocumentoSpesaOrdinativoConverter.class, SubdocumentoSpesaModelDetail.Ordinativo),
	SubdocumentoSpesaPredocumento(SubdocumentoSpesaPredocumentoConverter.class, SubdocumentoSpesaModelDetail.Predocumento),
	SubdocumentoSpesaProvvisorioDiCassa(SubdocumentoSpesaProvvisorioDiCassaConverter.class, SubdocumentoSpesaModelDetail.ProvvisorioDiCassa),
	SubdocumentoSpesaRegistroComunicazioniPCC(SubdocumentoSpesaRegistroComunicazioniPCCConverter.class, SubdocumentoSpesaModelDetail.RegistroComunicazioniPCC),
	SubdocumentoSpesaSedeSecondariaSoggetto(SubdocumentoSpesaSedeSecondariaSoggettoConverter.class, SubdocumentoSpesaModelDetail.SedeSecondariaSoggetto),
	SubdocumentoSpesaSubdocumentoIva(SubdocumentoSpesaSubdocumentoIvaConverter.class, SubdocumentoSpesaModelDetail.SubdocumentoIva),
	SubdocumentoSpesaTipoIvaSplitReverse(SubdocumentoSpesaTipoIvaSplitReverseConverter.class, SubdocumentoSpesaModelDetail.TipoIvaSplitReverse),
	SubdocumentoSpesaVoceMutuo(SubdocumentoSpesaVoceMutuoConverter.class, SubdocumentoSpesaModelDetail.VoceMutuo),
	SubdocumentoSpesaSiopeTipoDebito(SubdocumentoSpesaSiopeTipoDebitoConverter.class, SubdocumentoSpesaModelDetail.SiopeTipoDebito),
	SubdocumentoSpesaSiopeAssenzaMotivazione(SubdocumentoSpesaSiopeAssenzaMotivazioneConverter.class, SubdocumentoSpesaModelDetail.SiopeAssenzaMotivazione),
	SubdocumentoSpesaSiopeScadenzaMotivo(SubdocumentoSpesaSiopeScadenzaMotivoConverter.class, SubdocumentoSpesaModelDetail.SiopeScadenzaMotivo),
	SubdocumentoSpesaSospensioneSubdocumento(SubdocumentoSpesaSospensioneSubdocumentoConverter.class, SubdocumentoSpesaModelDetail.SospensioneSubdocumento),
	SubdocumentoSpesaNoteTesoriere(SubdocumentoSpesaNoteTesoriereConverter.class, SubdocumentoSpesaModelDetail.NoteTesoriere),
	SubdocumentoSpesaContoTesoreria(SubdocumentoSpesaContoTesoreriaConverter.class, SubdocumentoSpesaModelDetail.ContoTesoreria),
	SubdocumentoSpesaDocPadreModelDetail(SubdocumentoSpesaDocPadreModelDetailConverter.class, SubdocumentoSpesaModelDetail.DocPadreModelDetail),

	//SubdocumentoEntrata
	SubdocumentoEntrataAccertamentoSubaccertamento(SubdocumentoEntrataAccertamentoSubaccertamentoConverter.class, SubdocumentoEntrataModelDetail.AccertamentoSubaccertamento),
	SubdocumentoEntrataAccertamentoSubaccertamentoPdc(SubdocumentoEntrataAccertamentoSubaccertamentoPdcConverter.class, SubdocumentoEntrataModelDetail.AccertamentoSubaccertamentoPdc),
	SubdocumentoEntrataAttoAmm(SubdocumentoEntrataAttoAmmConverter.class, SubdocumentoEntrataModelDetail.AttoAmm),
	SubdocumentoEntrataAttr(SubdocumentoEntrataAttrConverter.class, SubdocumentoEntrataModelDetail.Attr),
	SubdocumentoEntrataClassif(SubdocumentoEntrataClassifConverter.class, SubdocumentoEntrataModelDetail.Classif),
	SubdocumentoEntrataCommissioniDocumento(SubdocumentoEntrataCommissioniDocumentoConverter.class, SubdocumentoEntrataModelDetail.CommissioniDocumento),
	SubdocumentoEntrataContoTesoreria(SubdocumentoEntrataContoTesoreriaConverter.class, SubdocumentoEntrataModelDetail.ContoTesoreria),
	SubdocumentoEntrataDistinta(SubdocumentoEntrataDistintaConverter.class, SubdocumentoEntrataModelDetail.Distinta),
	SubdocumentoEntrataDocPadre(SubdocumentoEntrataDocPadreConverter.class, SubdocumentoEntrataModelDetail.DocPadre),
	SubdocumentoEntrataTestataDocumento(SubdocumentoEntrataTestataDocumentoConverter.class,SubdocumentoEntrataModelDetail.TestataDocumento),
	SubdocumentoEntrataElencoDocumenti(SubdocumentoEntrataElencoDocumentiConverter.class, SubdocumentoEntrataModelDetail.ElencoDocumenti),
	SubdocumentoEntrataHasSubordinati(SubdocumentoEntrataHasSubordinatiConverter.class, SubdocumentoEntrataModelDetail.HasSubordinati),
	SubdocumentoEntrataIsSubordinato(SubdocumentoEntrataIsSubordinatoConverter.class, SubdocumentoEntrataModelDetail.IsSubordinato),
	SubdocumentoEntrataModPag(SubdocumentoEntrataModPagConverter.class, SubdocumentoEntrataModelDetail.ModPag),
	SubdocumentoEntrataOrdinativo(SubdocumentoEntrataOrdinativoConverter.class, SubdocumentoEntrataModelDetail.Ordinativo),
	SubdocumentoEntrataPredocumento(SubdocumentoEntrataPredocumentoConverter.class, SubdocumentoEntrataModelDetail.Predocumento),
	SubdocumentoEntrataProvvisorioDiCassa(SubdocumentoEntrataProvvisorioDiCassaConverter.class, SubdocumentoEntrataModelDetail.ProvvisorioDiCassa),
	SubdocumentoEntrataSedeSecondariaSoggetto(SubdocumentoEntrataSedeSecondariaSoggettoConverter.class, SubdocumentoEntrataModelDetail.SedeSecondariaSoggetto),
	SubdocumentoEntrataSubdocumentoIva(SubdocumentoEntrataSubdocumentoIvaConverter.class, SubdocumentoEntrataModelDetail.SubdocumentoIva),
	SubdocumentoEntrataDocPadreModelDetail(SubdocumentoEntrataDocPadreModelDetailConverter.class, SubdocumentoEntrataModelDetail.DocPadreModelDetail),
	
	//subdocumento iva
	SubdocumentoIvaRegistro(SubdocumentoIvaRegistroIvaConverter.class, SubdocumentoIvaModelDetail.RegistroIva),
	SubdocumentoIvaRegistroModelDetail(SubdocumentoIvaRegistroIvaModelDetailConverter.class, SubdocumentoIvaModelDetail.RegistroIvaModelDetail),
	
	// Accertamento
	AccertamentoAttoAmministrativo(MovimentoGestioneAttoAmministrativoConverter.class, AccertamentoModelDetail.AttoAmministrativo),
	AccertamentoCapitoloMinimal(AccertamentoCapitoloMinimalConverter.class, AccertamentoModelDetail.CapitoloMinimal),
	AccertamentoDisponibilitaIncassare(AccertamentoCalcolaDisponibilitaIncassareConverter.class, AccertamentoModelDetail.DisponibilitaIncassare),
	AccertamentoImporti(MovimentoGestioneImportiConverter.class, AccertamentoModelDetail.Importi),
	AccertamentoPianoDeiConti(MovimentoGestionePianoDeiContiConverter.class, AccertamentoModelDetail.PianoDeiConti),
	AccertamentoSoggetto(AccertamentoSoggettoConverter.class, AccertamentoModelDetail.Soggetto),
	AccertamentoClasseSoggetto(AccertamentoClasseSoggettoConverter.class, AccertamentoModelDetail.ClasseSoggetto),
	AccertamentoStato(AccertamentoStatoConverter.class, AccertamentoModelDetail.Stato),

	
	// SubAccertamento
	SubAccertamentoAttoAmministrativo(SubMovimentoGestioneAttoAmministrativoConverter.class, SubAccertamentoModelDetail.AttoAmministrativo),
	SubAccertamentoCapitoloMinimal(SubAccertamentoCapitoloMinimalConverter.class, SubAccertamentoModelDetail.CapitoloMinimal),
	SubAccertamentoSoggetto(MovimentoGestioneSoggettoConverter.class, SubAccertamentoModelDetail.Soggetto),
	SubAccertamentoClasseSoggetto(SubAccertamentoClasseSoggettoConverter.class, SubAccertamentoModelDetail.ClasseSoggetto),
	SubAccertamentoPianoDeiConti(MovimentoGestioneTestataSubPianoDeiContiConverter.class, SubAccertamentoModelDetail.PianoDeiConti),
	SubAccertamentoImporti(SubmovimentoGestioneImportiConverter.class, SubAccertamentoModelDetail.Importi),
	SubAccertamentoDisponibilitaIncassare(SubAccertamentoCalcolaDisponibilitaIncassareConverter.class, SubAccertamentoModelDetail.DisponibilitaIncassare),
	SubAccertamentoPadre(SubAccertamentoPadreConverter.class, SubAccertamentoModelDetail.Padre),
	SubAccertamentoStato(SubAccertamentoStatoConverter.class, SubAccertamentoModelDetail.Stato),
	
	// Impegno
	ImpegnoAttoAmministrativo(MovimentoGestioneAttoAmministrativoConverter.class, ImpegnoModelDetail.AttoAmministrativo),
	ImpegnoCapitoloMinimal(ImpegnoCapitoloMinimalConverter.class, ImpegnoModelDetail.CapitoloMinimal),
	ImpegnoSoggetto(ImpegnoSoggettoConverter.class, ImpegnoModelDetail.Soggetto),
	ImpegnoPianoDeiConti(MovimentoGestionePianoDeiContiConverter.class, ImpegnoModelDetail.PianoDeiConti),
	ImpegnoImporti(MovimentoGestioneImportiConverter.class, ImpegnoModelDetail.Importi),
	ImpegnoDisponibilitaIncassare(ImpegnoCalcolaDisponibilitaLiquidareConverter.class, ImpegnoModelDetail.DisponibilitaLiquidare),
	ImpegnoStato(ImpegnoStatoConverter.class, ImpegnoModelDetail.Stato),
	ImpegnoClasseSoggetto(ImpegnoClasseSoggettoConverter.class, ImpegnoModelDetail.ClasseSoggetto),
	ImpegnoSiopeTipoDebito(ImpegnoSiopeTipoDebitoConverter.class, ImpegnoModelDetail.SiopeTipoDebito),
	ImpegnoSiopeAssenzaMotivazione(ImpegnoSiopeAssenzaMotivazioneConverter.class, ImpegnoModelDetail.SiopeAssenzaMotivazione),
	ImpegnoCigCup(ImpegnoCigCupConverter.class, ImpegnoModelDetail.CigCup),
	
	// SubImpegno
	SubImpegnoAttoAmministrativo(SubMovimentoGestioneAttoAmministrativoConverter.class, SubImpegnoModelDetail.AttoAmministrativo),
	SubImpegnoCapitoloMinimal(SubImpegnoCapitoloMinimalConverter.class, SubImpegnoModelDetail.CapitoloMinimal),
	SubImpegnoSoggetto(MovimentoGestioneSoggettoConverter.class, SubImpegnoModelDetail.Soggetto),
	SubImpegnoPianoDeiConti(MovimentoGestioneTestataSubPianoDeiContiConverter.class, SubImpegnoModelDetail.PianoDeiConti),
	SubImpegnoImporti(SubmovimentoGestioneImportiConverter.class, SubImpegnoModelDetail.Importi),
	SubImpegnoDisponibilitaIncassare(SubImpegnoCalcolaDisponibilitaLiquidareConverter.class, SubImpegnoModelDetail.DisponibilitaLiquidare),
	SubImpegnoPadre(SubImpegnoPadreConverter.class, SubImpegnoModelDetail.Padre),
	SubImpegnoStato(SubImpegnoStatoConverter.class, SubImpegnoModelDetail.Stato),
	SubImpegnoClasseSoggetto(SubImpegnoClasseSoggettoConverter.class, SubImpegnoModelDetail.ClasseSoggetto),
	SubImpegnoSiopeTipoDebito(SubImpegnoSiopeTipoDebitoConverter.class, SubImpegnoModelDetail.SiopeTipoDebito),
	SubImpegnoSiopeAssenzaMotivazione(SubImpegnoSiopeAssenzaMotivazioneConverter.class, SubImpegnoModelDetail.SiopeAssenzaMotivazione),
	SubImpegnoCigCup(SubImpegnoCigCupConverter.class, SubImpegnoModelDetail.CigCup),
	
	// Liquidazione
	LiquidazioneImpegno(LiquidazioneImpegnoConverter.class, LiquidazioneModelDetail.Impegno),
	LiquidazioneImpegnoPdc(LiquidazioneImpegnoPianoDeiContiConverter.class, LiquidazioneModelDetail.ImpegnoPianoDeiConti),
	LiquidazionePianoDeiConti(LiquidazionePianoDeiContiConverter.class, LiquidazioneModelDetail.PianoDeiConti),
	LiquidazioneSoggetto(LiquidazioneSoggettoConverter.class, LiquidazioneModelDetail.Soggetto),
	LiquidazioneStato(LiquidazioneStatoConverter.class, LiquidazioneModelDetail.Stato),
	LiquidazioneSiopeTipoDebito(LiquidazioneSiopeTipoDebitoConverter.class, LiquidazioneModelDetail.SiopeTipoDebito),
	LiquidazioneSiopeAssenzaMotivazione(LiquidazioneSiopeAssenzaMotivazioneConverter.class, LiquidazioneModelDetail.SiopeAssenzaMotivazione),
	
	//BilElemStato(BilElemStatoConverter.class, AllegatoAttoModelDetail.ElencoDocumenti),
	
	// SIAC-4088
	AccantonamentoFondiDubbiaEsigibilitaCapitoloEntrataPrevisione(AccantonamentoFondiDubbiaEsigibilitaCapitoloConverter.class, AccantonamentoFondiDubbiaEsigibilitaModelDetail.CapitoloEntrataPrevisione),
	
	// StampeCassaFile
	StampeCassaFileCassaEconomale(StampeCassaFileCassaEconomaleConverter.class, StampeCassaFileModelDetail.CassaEconomale),
	StampeCassaFileBilancio(StampeCassaFileBilancioConverter.class, StampeCassaFileModelDetail.Bilancio),
	StampeCassaFileTipoDocumento(StampeCassaFileTipoDocumentoConverter.class, StampeCassaFileModelDetail.TipoDocumento),
	StampeCassaFileStatoStampa(StampeCassaFileStatoStampaConverter.class, StampeCassaFileModelDetail.StatoStampa),
	StampeCassaFileValore(StampeCassaFileValoreConverter.class, StampeCassaFileModelDetail.Valore),
	StampeCassaFileFile(StampeCassaFileFileConverter.class, StampeCassaFileModelDetail.File),
	StampeCassaFileOperazioneCassa(StampeCassaFileOperazioneCassaConverter.class, StampeCassaFileModelDetail.OperazioneCassa),
	StampeCassaFileMovimento(StampeCassaFileMovimentoConverter.class, StampeCassaFileModelDetail.Movimento),
	StampeCassaFileAllegatoAtto(StampeCassaFileAllegatoAttoConverter.class, StampeCassaFileModelDetail.AllegatoAtto),
	
	// SIAC-4422
	AccantonamentoFondiDubbiaEsigibilitaRendicontoCapitoloEntrataGestione(AccantonamentoFondiDubbiaEsigibilitaRendicontoCapitoloConverter.class, AccantonamentoFondiDubbiaEsigibilitaRendicontoModelDetail.CapitoloEntrataGestione),
	
	//RichiestaEconomale
	RichiestaEconomaleCassaEconomale(RichiestaEconomaleCassaEconomaleConverter.class, RichiestaEconomaleModelDetail.CassaEconomale),
	RichiestaEconomaleStatoOperativo(RichiestaEconomaleStatoOperativoConverter.class, RichiestaEconomaleModelDetail.StatoOperativo),
	RichiestaEconomaleRendiconto(RichiestaEconomaleRendicontoConverter.class, RichiestaEconomaleModelDetail.Rendiconto),
	RichiestaEconomaleRendicontoConMovimentoBase(RichiestaEconomaleRendicontoConMovimentoBaseConverter.class, RichiestaEconomaleModelDetail.RendicontoConMovimentoBase),
	RichiestaEconomaleCassaEconomaleMinimal(RichiestaEconomaleCassaEconomaleMinimalConverter.class, RichiestaEconomaleModelDetail.CassaEconomaleMinimal),
	RichiestaEconomaleSospeso(RichiestaEconomaleSospesoConverter.class, RichiestaEconomaleModelDetail.Sospeso),
	RichiestaEconomaleSoggetto(RichiestaEconomaleSoggettoConverter.class, RichiestaEconomaleModelDetail.Soggetto),
	RichiestaEconomaleMovimenti(RichiestaEconomaleMovimentiConverter.class, RichiestaEconomaleModelDetail.Movimenti),
	RichiestaEconomaleImpegno(RichiestaEconomaleImpegnoConverter.class, RichiestaEconomaleModelDetail.Impegno),
	RichiestaEconomaleClassificatori(RichiestaEconomaleClassificatoriConverter.class, RichiestaEconomaleModelDetail.Classificatori),
	RichiestaEconomaleDatiTrasferta(RichiestaEconomaleDatiTrasfertaConverter.class, RichiestaEconomaleModelDetail.DatiTrasferta),
	RichiestaEconomaleGiustificativi(RichiestaEconomaleGiustificativiConverter.class, RichiestaEconomaleModelDetail.Giustificativi),
	RichiestaEconomaleSubdocumento(RichiestaEconomaleSubdocumentoConverter.class, RichiestaEconomaleModelDetail.Subdocumento),
	RichiestaEconomaleDatiStampa(RichiestaEconomaleDatiStampaConverter.class, RichiestaEconomaleModelDetail.DatiStampa),
	
	//AttoAmministrativo
	AttoAmministrativoSac(AttoAmministrativoSacConverter.class, AttoAmministrativoModelDetail.StrutturaAmmContabile),
	AttoAmministrativoTipoAtto(AttoAmministrativoTipoAttoConverter.class, AttoAmministrativoModelDetail.TipoAtto),
	AttoAmministrativoStatoOperativo(AttoAmministrativoStatoOperativoConverter.class, AttoAmministrativoModelDetail.StatoOperativo),
	AttoAmministrativoAllegatoAtto(AttoAmministrativoAllegatoAttoConverter.class, AttoAmministrativoModelDetail.AllegatoAtto),
	
	// SIAC-4996
	// PredocumentoSpesa
	PreDocumentoSpesaAttoAmm(PreDocumentoAttoAmmConverter.class, PreDocumentoSpesaModelDetail.AttoAmm),
	PreDocumentoSpesaCapitolo(PreDocumentoSpesaCapitoloConverter.class, PreDocumentoSpesaModelDetail.Capitolo),
	PreDocumentoSpesaCausale(PreDocumentoSpesaCausaleConverter.class, PreDocumentoSpesaModelDetail.Causale),
	PreDocumentoSpesaClassif(PreDocumentoClassifConverter.class, PreDocumentoSpesaModelDetail.Classif),
	PreDocumentoSpesaContoTesoreria(PreDocumentoSpesaContoTesoreriaConverter.class, PreDocumentoSpesaModelDetail.ContoTesoreria),
	PreDocumentoSpesaDatiAnagrafici(PreDocumentoSpesaDatiAnagraficiConverter.class, PreDocumentoSpesaModelDetail.DatiAnagrafici),
	PreDocumentoSpesaElencoDocumentiAllegato(PreDocumentoElencoDocumentiAllegatoConverter.class, PreDocumentoSpesaModelDetail.ElencoDocumentiAllegato),
	PreDocumentoSpesaImpegno(PreDocumentoSpesaImpegnoConverter.class, PreDocumentoSpesaModelDetail.Impegno),
	PreDocumentoSpesaImpegnoModelDetail(PreDocumentoSpesaImpegnoModelDetailConverter.class, PreDocumentoSpesaModelDetail.ImpegnoModelDetail),
	PreDocumentoSpesaModPag(PreDocumentoSpesaModPagConverter.class, PreDocumentoSpesaModelDetail.ModPag),
	PreDocumentoSpesaProvvisorioDiCassa(PreDocumentoProvvisorioDiCassaConverter.class, PreDocumentoSpesaModelDetail.ProvvisorioDiCassa),
	PreDocumentoSpesaSogg(PreDocumentoSoggConverter.class, PreDocumentoSpesaModelDetail.Sogg),
	PreDocumentoSpesaStato(PreDocumentoStatoConverter.class, PreDocumentoSpesaModelDetail.Stato),
	PreDocumentoSpesaSubDocumento(PreDocumentoSpesaSubDocumentoConverter.class, PreDocumentoSpesaModelDetail.SubDocumento),
	PreDocumentoSpesaVoceMutuo(PreDocumentoSpesaVoceMutuoConverter.class, PreDocumentoSpesaModelDetail.VoceMutuo),
	
	// PreDocumentoEntrata
	PreDocumentoEntrataAccertamento(PreDocumentoEntrataAccertamentoConverter.class, PreDocumentoEntrataModelDetail.Accertamento),
	PreDocumentoEntrataAttoAmm(PreDocumentoAttoAmmConverter.class, PreDocumentoEntrataModelDetail.AttoAmm),
	PreDocumentoEntrataCapitolo(PreDocumentoEntrataCapitoloConverter.class, PreDocumentoEntrataModelDetail.Capitolo),
	PreDocumentoEntrataCausale(PreDocumentoEntrataCausaleConverter.class, PreDocumentoEntrataModelDetail.Causale),
	PreDocumentoEntrataClassif(PreDocumentoEntrataClassifConverter.class, PreDocumentoEntrataModelDetail.Classif),
	PreDocumentoEntrataDatiAnagrafici(PreDocumentoEntrataDatiAnagraficiConverter.class, PreDocumentoEntrataModelDetail.DatiAnagrafici),
	PreDocumentoEntrataElencoDocumentiAllegato(PreDocumentoElencoDocumentiAllegatoConverter.class, PreDocumentoEntrataModelDetail.ElencoDocumentiAllegato),
	PreDocumentoEntrataProvvisorioDiCassa(PreDocumentoProvvisorioDiCassaConverter.class, PreDocumentoEntrataModelDetail.ProvvisorioDiCassa),
	PreDocumentoEntrataSogg(PreDocumentoSoggConverter.class, PreDocumentoEntrataModelDetail.Sogg),
	PreDocumentoEntrataStato(PreDocumentoStatoConverter.class, PreDocumentoEntrataModelDetail.Stato),
	PreDocumentoEntrataSubDocumento(PreDocumentoEntrataSubDocumentoConverter.class, PreDocumentoEntrataModelDetail.SubDocumento),
	
	// ElencoDocumentiAllegato
	ElencoDocumentiAllegatoAttoAllegato(ElencoDocAttoAllegatoConverter.class, ElencoDocumentiAllegatoModelDetail.AttoAllegato),
	ElencoDocumentiAllegatoAttoAllegatoExtended(ElencoDocAttoAllegatoExtendedConverter.class, ElencoDocumentiAllegatoModelDetail.AttoAllegatoExtended),
	ElencoDocumentiAllegatoStato(ElencoDocStatoConverter.class, ElencoDocumentiAllegatoModelDetail.Stato),
	ElencoDocumentiAllegatoSubdocumenti(ElencoDocSubdocumentiConverter.class, ElencoDocumentiAllegatoModelDetail.Subdocumenti),
	ElencoDocumentiAllegatoSubdocumentiDettaglio(ElencoDocSubdocumentiDettaglioConverter.class, ElencoDocumentiAllegatoModelDetail.SubdocumentiDettaglio),
	ElencoDocumentiAllegatoContieneQuoteACopertura(ElencoDocContieneQuoteACoperturaConverter.class, ElencoDocumentiAllegatoModelDetail.ContieneQuoteACopertura),
	ElencoDocumentiAllegatoSubdocumentiTotale(ElencoDocSubdocumentiTotaleConverter.class, ElencoDocumentiAllegatoModelDetail.SubdocumentiTotale),
	ElencoDocumentiAllegatoTotaleDaConvalidareSpesaEntrata(ElencoDocTotaleDaConvalidareSpesaEntrataConverter.class, ElencoDocumentiAllegatoModelDetail.TotaleDaConvalidareSpesaEntrata),
	ElencoDocumentiAllegatoTotaleDaPagareIncassare(ElencoDocTotaleDaPagareIncassareConverter.class, ElencoDocumentiAllegatoModelDetail.TotaleDaPagareIncassare),
	ElencoDocumentiAllegatoTotaleQuoteSpesaEntrata(ElencoDocTotaleQuoteSpesaEntrataConverter.class, ElencoDocumentiAllegatoModelDetail.TotaleQuoteSpesaEntrata),
	ElencoDocumentiAllegatoHasImpegnoConfermaDataFineValiditaDurc(ElencoDocImpegnoConfermaDataFineValiditaDurcConverter.class, ElencoDocumentiAllegatoModelDetail.HasImpegnoConfermaDataFineValiditaDurc),
	
	// Variazione
	VariazioneImportoCapitoloBilancio(VariazioneBilancioConverter.class, VariazioneImportoCapitoloModelDetail.Bilancio),
	
	//SIAC-5336
	ClassificatoreGSAClassificatoreGSAPadre(ClassificatoreGSAClassificatoreGSAPadreConverter.class, ClassificatoreGSAModelDetail.ClassificatoreGSAPadre),
	ClassificatoreGSAClassificatoreGSAFigli(ClassificatoreGSAClassificatoreGSAFigliConverter.class, ClassificatoreGSAModelDetail.ClassificatoreGSAFigli),
	ClassificatoreGSAClassificatoreGSAAmbito(ClassificatoreGSAAmbitoConverter.class, ClassificatoreGSAModelDetail.Ambito),
	ClassificatoreGSAClassificatoreGSAStato(ClassificatoreGSAStatoConverter.class, ClassificatoreGSAModelDetail.Stato),
		
	PrimaNotaTipoCausaleConverter( PrimaNotaTipoCausaleConverter.class, PrimaNotaModelDetail.TipoCausale),
	PrimaNotaAmbito(PrimaNotaAmbitoConverter.class, PrimaNotaModelDetail.Ambito),
	PrimaNotaBilancio(PrimaNotaBilancioConverter.class, PrimaNotaModelDetail.Bilancio),
	PrimaNotaStatoOperativo(PrimaNotaStatoOperativoConverter.class, PrimaNotaModelDetail.StatoOperativo),
	PrimaNotaRateoRisconto( PrimaNotaRateoRiscontoConverter.class, PrimaNotaModelDetail.RateoRisconto),
//	PrimaNotaSoggetto(PrimaNotaSoggettoConverter.class, PrimaNotaModelDetail.Soggetto),
	PrimaNotaMovimentiEp(PrimaNotaMovimentiEpConverter.class, PrimaNotaModelDetail.MovimentiEp),
	PrimaNotaMovimentiEpModelDetail(PrimaNotaMovimentiEpModelDetailConverter.class, PrimaNotaModelDetail.MovimentiEpModelDetail),
	PrimaNotaMovimentiEpDettaglioContoModelDetail(PrimaNotaMovimentiEpDettaglioContoConverter.class, PrimaNotaModelDetail.MovimentiEpDettaglioConto),
//	PrimaNotaMovimentiEpRegistrazioneMovFinWithLogicalKey(  PrimaNotaMovimentiEpRegistrazioneMovFinWithLogicalKey, Converter.class, PrimaNotaModelDetail.MovimentiEpRegistrazioneMovFinWithLogicalKey),
//	PrimaNotaPrimeNoteCollegate(                            PrimaNotaPrimeNoteCollegateConverter.class, PrimaNotaModelDetail.PrimeNoteCollegate),
	PrimaNotaStatoAccettazionePrimaNotaProvvisoria(PrimaNotaStatoAccettazionePrimaNotaProvvisoriaConverter.class, PrimaNotaModelDetail.StatoAccettazionePrimaNotaProvvisoria),
	PrimaNotaStatoAccettazionePrimaNotaDefinitiva(PrimaNotaStatoAccettazionePrimaNotaDefinitivaConverter.class, PrimaNotaModelDetail.StatoAccettazionePrimaNotaDefinitiva),
	PrimaNotaContoInventario(PrimaNotaContoInventarioConverter.class, PrimaNotaModelDetail.ContoInventario),
	PrimaNotaPrimaNotaInventario(PrimaNotaPrimaNotaInventarioConverter.class, PrimaNotaModelDetail.PrimaNotaInventario),
	PrimaNotaSoggetto(PrimaNotaSoggettoConverter.class, PrimaNotaModelDetail.Soggetto),
	
	MovimentoEpCausaleEPModelDetailModelDetail(MovimentoEPCausaleEPModelDetailConverter.class, MovimentoEPModelDetail.CausaleEPModelDetail),
	MovimentoEpMovimentoDettaglioModelDetail(MovimentoEPMovimentoDettaglioContoConverter.class, MovimentoEPModelDetail.MovimentoDettaglio),
	MovimentoEpMovimentoDettaglioModelDetailModelDetail(MovimentoEPMovimentoDettaglioModelDetailConverter.class, MovimentoEPModelDetail.MovimentoDettaglioModelDetail),
	MovimentoEpMovimentoRegistrazioneMovFinModelDetailModelDetail(MovimentoEPRegistrazioneMovFInModelDetailConverter.class, MovimentoEPModelDetail.RegistrazioneMovFinModelDetail),
	MovimentoEpMovimentoPrimaNotaModelDetailModelDetail(MovimentoEPPrimaNotaModelDetailConverter.class, MovimentoEPModelDetail.PrimaNotaModelDetail),
	
	RegistrazioneMovFinAmbitoModelDetail(RegistrazioneMovFinAmbitoConverter.class, RegistrazioneMovFinModelDetail.Ambito),                       
	RegistrazioneMovFinEventoMovimentoModelDetail(RegistrazioneMovFinEventoMovimentoConverter.class, RegistrazioneMovFinModelDetail.EventoMovimento),             
	RegistrazioneMovFinEventoMovimentoLightModelDetail(RegistrazioneMovFinEventoMovimentoLightConverter.class, RegistrazioneMovFinModelDetail.EventoMovimentoLight),        
	RegistrazioneMovFinIsCollegataAMovimentoResiduoModelDetail(RegistrazioneMovFinIsCollegataAMovimentoResiduoConverter.class, RegistrazioneMovFinModelDetail.IsCollegataAMovimentoResiduo),
	RegistrazioneMovFinMovimentiEPModelDetail(RegistrazioneMovFinMovimentiEPConverter.class, RegistrazioneMovFinModelDetail.MovimentiEP),                 
	RegistrazioneMovFinStatoModelDetail(RegistrazioneMovFinStatoConverter.class, RegistrazioneMovFinModelDetail.Stato),  
	RegistrazioneMovFinPianoDeiContiModelDetail(RegistrazioneMovFinPianoDeiContiConverter.class, RegistrazioneMovFinModelDetail.PianoDeiConti),  
	
	MovimentoDettaglioAmbitoModelDetail(MovimentoDettaglioAmbitoConverter.class, MovimentoDettaglioModelDetail.Ambito), 
	MovimentoDettaglioSegnoModelDetail(MovimentoDettaglioSegnoConverter.class, MovimentoDettaglioModelDetail.Segno),  
	MovimentoDettaglioContoModelDetail(MovimentoDettaglioContoConverter.class, MovimentoDettaglioModelDetail.Conto),
	MovimentoDettaglioContoModelDetailModelDetail(MovimentoDettaglioContoModelDetailConverter.class, MovimentoDettaglioModelDetail.ContoModelDetail),
	MovimentoDettaglioMovimentoEPModelDetailModelDetail(MovimentoDettaglioMovimentoEPModelDetailConverter.class, MovimentoDettaglioModelDetail.MovimentoEPModelDetail),
	MovimentoDettaglioClassifModelDetail(MovimentoDettaglioClassifConverter.class, MovimentoDettaglioModelDetail.Classif),
	MovimentoDettaglioCespitiModelDetail(MovimentoDettaglioCespiteConverter.class, MovimentoDettaglioModelDetail.Cespiti),
	MovimentoDettaglioImportoInventariatoModelDetail(MovimentoDettaglioImportoInventariatoConverter.class, MovimentoDettaglioModelDetail.ImportoInventariato),
	
	
	// Progetto
	ProgettoCronoprogrammi(ProgettoCronoprogrammiConverter.class, ProgettoModelDetail.Cronoprogrammi),

	
	//TIPO BENE CESPITI
	TipoBeneCespiteCategoriaCespitiModelDetail(TipoBeneCespiteCategoriaCespitiConverter.class, TipoBeneCespiteModelDetail.CategoriaCespiti),
	TipoBeneCespiteCategoriaCespitiModelDetailModelDetail(TipoBeneCespiteCategoriaCespitiModelDetailConverter.class, TipoBeneCespiteModelDetail.CategoriaCespitiModelDetail),
	TipoBeneCespiteContoPatrimonialeModelDetail(TipoBeneCespiteContoPatrimonialeConverter.class, TipoBeneCespiteModelDetail.ContoPatrimoniale),

	
	TipoBeneCespiteEventoAmmortamentoeModelDetail(TipoBeneCespiteEventoAmmortamentoConverter.class, TipoBeneCespiteModelDetail.EventoAmmortamento),
	TipoBeneCespiteCausaleAmmortamentoeModelDetail(TipoBeneCespiteCausaleEPAmmortamentoConverter.class, TipoBeneCespiteModelDetail.CausaleAmmortamento),
	TipoBeneCespiteContoAmmortamentoeModelDetail(TipoBeneCespiteContoAmmortamentoConverter.class, TipoBeneCespiteModelDetail.ContoAmmortamento),
	
	TipoBeneCespiteEventoIncrementoeModelDetail(TipoBeneCespiteEventoIncrementoConverter.class, TipoBeneCespiteModelDetail.EventoIncremento),
	TipoBeneCespiteCausaleIncrementoeModelDetail(TipoBeneCespiteCausaleEPIncrementoConverter.class, TipoBeneCespiteModelDetail.CausaleIncremento),
	TipoBeneCespiteContoIncrementoeModelDetail(TipoBeneCespiteContoIncrementoConverter.class, TipoBeneCespiteModelDetail.ContoIncremento),
	
	TipoBeneCespiteEventoDecrementoeModelDetail(TipoBeneCespiteEventoDecrementoConverter.class, TipoBeneCespiteModelDetail.EventoDecremento),
	TipoBeneCespiteCausaleDecrementoeModelDetail(TipoBeneCespiteCausaleEPDecrementoConverter.class, TipoBeneCespiteModelDetail.CausaleDecremento),
	TipoBeneCespiteContoDecrementoeModelDetail(TipoBeneCespiteContoDecrementoConverter.class, TipoBeneCespiteModelDetail.ContoDecremento),
	
	TipoBeneCespiteContoFondoAmmortamentoeModelDetail(TipoBeneCespiteContoFondoAmmortamentoConverter.class, TipoBeneCespiteModelDetail.ContoFondoAmmortamento),
	TipoBeneCespiteContoPlusvalenzaeModelDetail(TipoBeneCespiteContoPlusvalenzaConverter.class, TipoBeneCespiteModelDetail.ContoPlusvalenza),
	TipoBeneCespiteContoMinusValenzaeModelDetail(TipoBeneCespiteContoMinusvalenzaConverter.class, TipoBeneCespiteModelDetail.ContoMinusValenza),
	TipoBeneCespiteContoAlienazioneeModelDetail(TipoBeneCespiteContoAlienazioneConverter.class, TipoBeneCespiteModelDetail.ContoAlienazione),
	TipoBeneCespiteContoDonazioneModelDetail(TipoBeneCespiteContoDonazioneConverter.class, TipoBeneCespiteModelDetail.ContoDonazione),
	TipoBeneCespiteAnnullatoModelDetail(TipoBeneCespiteFlagAnnullatoConverter.class, TipoBeneCespiteModelDetail.Annullato),
	//categoria cespite
	CategoriaCespitiTipoCalcoloModelDetail(CategoriaCespitiTipoCalcoloConverter.class, CategoriaCespitiModelDetail.TipoCalcolo),
	CategoriaCespitiAliquotaAnnuaModelDetail(CategoriaCespitiAliquotaAnnuaConverter.class, CategoriaCespitiModelDetail.AliquotaAnnua),
	CategoriaCespitiAnnullatoModelDetail(CategoriaCespitiAnnullatoConverter.class, CategoriaCespitiModelDetail.Annullato),
	//cespite 
	CespiteTipoBeneCespiteModelDetail(CespiteTipoBeneCespiteConverter.class, CespiteModelDetail.TipoBeneCespite),
	CespiteTipoBeneCespiteModelDetailModelDetail(CespiteTipoBeneCespiteModelDetailConverter.class, CespiteModelDetail.TipoBeneCespiteModelDetail),
	CespiteClassificazioneGiuridicaModelDetail(CespiteClassificazioneGiuridicaConverter.class, CespiteModelDetail.ClassificazioneGiuridicaCespite),
	CespiteFondoAmmortamentoModelDetail(CespiteFondoAmmortamentoConverter.class, CespiteModelDetail.FondoAmmortamento),
	CespiteDismissioneCespiteModelDetail(CespiteDismissioneCespiteConverter.class, CespiteModelDetail.DismissioneCespite),
	CespiteIsCollegatoAPrimeNoteModelDetail(CespiteIsCollegatoAPrimeNoteConverter.class, CespiteModelDetail.IsCollegatoAPrimeNote),
	CespiteAmmortamentoAnnuoCespiteModelDetailModelDetail(CespiteAmmortamentoAnnuoCespiteModelDetailConverter.class, CespiteModelDetail.AmmortamentoAnnuoCespiteModelDetail),
	CespiteIsInserimentoContestualeRegistroAModelDetail(CespiteIsInserimentoContestualeRegistroAConverter.class, CespiteModelDetail.IsInserimentoContestualeRegistroA),
	CespiteValoreAttualeSuRegistroAModelDetail(CespiteImportoSuRegistroAConverter.class, CespiteModelDetail.ImportoSuRegistroA),
	//
	// VariazioneCespite
	VariazioneCespiteStatoVariazioneCespiteModelDetail(VariazioneCespiteStatoVariazioneCespiteConverter.class, VariazioneCespiteModelDetail.StatoVariazioneCespite),
	VariazioneCespiteCespiteModelDetail(VariazioneCespiteCespiteConverter.class, VariazioneCespiteModelDetail.Cespite),
	VariazioneCespiteCespiteModelDetailModelDetail(VariazioneCespiteCespiteModelDetailConverter.class, VariazioneCespiteModelDetail.CespiteModelDetail),
	
	DismissioneCespiteNumeroCespitiCollegatiModelDetail(DismissioneCespiteNumeroCespitiCollegatiConverter.class,DismissioneCespiteModelDetail.NumeroCespitiCollegati),
	DismissioneCespiteAttoAmministrativoModelDetail(DismissioneCespiteAttoAmmConverter.class, DismissioneCespiteModelDetail.AttoAmministrativo),
	DismissioneCespiteCausaleEPModelDetail(DismissioneCespiteCausaleEPConverter.class, DismissioneCespiteModelDetail.CausaleEP),
	DismissioneCespiteEventoModelDetail(DismissioneCespiteEventoConverter.class, DismissioneCespiteModelDetail.Evento),
	DismissioneCespiteStatoDismissioneCespiteModelDetail(DismissioneCespiteStatoDismissioneCespiteConverter.class, DismissioneCespiteModelDetail.Stato),
	
	AmmortamentoAnnuoCespiteDettaglioAmmortamentoAnnuoCespiteModelDetail(AmmortamentoAnnuoCespiteDettaglioAmmortamentoAnnuoCespiteConverter.class,AmmortamentoAnnuoCespiteModelDetail.DettaglioAmmortamentoAnnuoCespite),
	AmmortamentoAnnuoCespiteDettaglioAmmortamentoAnnuoCespiteModelDetailModelDetail(AmmortamentoAnnuoCespiteDettaglioAmmortamentoAnnuoCespiteModelDetailConverter.class,AmmortamentoAnnuoCespiteModelDetail.DettaglioAmmortamentoAnnuoCespiteModelDetail),
	AmmortamentoAnnuoCespiteDettaglioAmmortamentoAnnuoCespiteAnnoSpecificoModelDetailModelDetail(AmmortamentoAnnuoCespiteDettaglioAmmortamentoAnnuoCespiteAnnoSpecificoConverter.class,AmmortamentoAnnuoCespiteModelDetail.DettaglioAmmortamentoAnnuoCespiteAnnoSpecificoModelDetail),
	AmmortamentoAnnuoCespiteCespiteModelDetail(AmmortamentoAnnuoCespiteCespiteConverter.class,AmmortamentoAnnuoCespiteModelDetail.Cespite),
	
	DettaglioAmmortamentoAnnuoCespiteAmmortamentoAnnuoCespiteModelDetail(DettaglioAmmortamentoAnnuoCespiteAmmortamentoAnnuoCespiteConverter.class, DettaglioAmmortamentoAnnuoCespiteModelDetail.AmmortamentoAnnuoCespite),
	DettaglioAmmortamentoAnnuoCespiteAmmortamentoAnnuoCespiteModelDetailModelDetail(DettaglioAmmortamentoAnnuoCespiteAmmortamentoAnnuoCespiteModelDetailConverter.class, DettaglioAmmortamentoAnnuoCespiteModelDetail.AmmortamentoAnnuoCespiteModelDetail),
	DettaglioAmmortamentoAnnuoCespitePrimaNotaModelDetail(DettaglioAmmortamentoAnnuoCespitePrimaNotaConverter.class, DettaglioAmmortamentoAnnuoCespiteModelDetail.PrimaNota),
	DettaglioAmmortamentoAnnuoCespitePrimaNotaModelDetailModelDetail(DettaglioAmmortamentoAnnuoCespitePrimaNotaModelDetailConverter.class, DettaglioAmmortamentoAnnuoCespiteModelDetail.PrimaNotaModelDetail),
	
	DettaglioAnteprimaAmmortamentoAnnuoCespiteSegnoModelDetail(DettaglioAnteprimaAmmortamentoAnnuoCespiteSegnoConverter.class,DettaglioAnteprimaAmmortamentoAnnuoCespiteModelDetail.Segno),
	DettaglioAnteprimaAmmortamentoAnnuoCespiteAnteprimaModelDetail(DettaglioAnteprimaAmmortamentoAnnuoCespiteAnteprimaConverter.class,DettaglioAnteprimaAmmortamentoAnnuoCespiteModelDetail.AnteprimaAmmortamento), 
	DettaglioAnteprimaAmmortamentoAnnuoCespiteContoModelDetail(DettaglioAnteprimaAmmortamentoAnnuoCespiteContoConverter.class,DettaglioAnteprimaAmmortamentoAnnuoCespiteModelDetail.Conto),
	
	//SIAC-6255
	QuadroEconomicoParteModelDetail(QuadroEconomicoParteConverter.class,QuadroEconomicoModelDetail.Parte),
	
	// SIAC-6881
	ComponenteImportiCapitoloImportoModelDetail(ComponenteImportiCapitoloImportoConverter.class, ComponenteImportiCapitoloModelDetail.Importo),
	ComponenteImportiCapitoloImportiCapitoloModelDetail(ComponenteImportiCapitoloImportiCapitoloConverter.class, ComponenteImportiCapitoloModelDetail.ImportiCapitolo),
	ComponenteImportiCapitoloTipoComponenteImportiCapitoloModelDetail(ComponenteImportiCapitoloTipoComponenteImportiCapitoloConverter.class, ComponenteImportiCapitoloModelDetail.TipoComponenteImportiCapitolo),
	ComponenteImportiCapitoloHasVariazioniModelDetail(ComponenteImportiCapitoloHasVariazioniConverter.class, ComponenteImportiCapitoloModelDetail.HasVariazioni),
	
	TipoComponenteImportiCapitoloAmbitoComponenteImportiCapitoloModelDetail(TipoComponenteImportiCapitoloAmbitoComponenteImportiCapitoloConverter.class, TipoComponenteImportiCapitoloModelDetail.AmbitoComponenteImportiCapitolo),
	TipoComponenteImportiCapitoloAnnoModelDetail(TipoComponenteImportiCapitoloAnnoConverter.class, TipoComponenteImportiCapitoloModelDetail.Anno),
	TipoComponenteImportiCapitoloFonteFinanziariaComponenteImportiCapitoloModelDetail(TipoComponenteImportiCapitoloFonteFinanziariaComponenteImportiCapitoloConverter.class, TipoComponenteImportiCapitoloModelDetail.FonteFinanziariaComponenteImportiCapitolo),
	TipoComponenteImportiCapitoloMacrotipoComponenteImportiCapitoloModelDetail(TipoComponenteImportiCapitoloMacrotipoComponenteImportiCapitoloConverter.class, TipoComponenteImportiCapitoloModelDetail.MacrotipoComponenteImportiCapitolo),
	TipoComponenteImportiCapitoloSottotipoComponenteImportiCapitoloModelDetail(TipoComponenteImportiCapitoloSottotipoComponenteImportiCapitoloConverter.class, TipoComponenteImportiCapitoloModelDetail.SottotipoComponenteImportiCapitolo),
	TipoComponenteImportiCapitoloMomentoComponenteImportiCapitoloModelDetail(TipoComponenteImportiCapitoloMomentoComponenteImportiCapitoloConverter.class, TipoComponenteImportiCapitoloModelDetail.MomentoComponenteImportiCapitolo),
	TipoComponenteImportiCapitoloPropostaDefaultComponenteImportiCapitoloModelDetail(TipoComponenteImportiCapitoloPropostaDefaultComponenteImportiCapitoloConverter.class, TipoComponenteImportiCapitoloModelDetail.PropostaDefaultComponenteImportiCapitolo),
	TipoComponenteImportiCapitoloTipoGestioneComponenteImportiCapitoloModelDetail(TipoComponenteImportiCapitoloTipoGestioneComponenteImportiCapitoloConverter.class, TipoComponenteImportiCapitoloModelDetail.TipoGestioneComponenteImportiCapitolo),
	TipoComponenteImportiCapitoloDettaglioComponenteImportiCapitoloModelDetail(TipoComponenteImportiCapitoloDettaglioComponenteImportiCapitoloConverter.class, TipoComponenteImportiCapitoloModelDetail.DettaglioComponenteImportiCapitolo),
	TipoComponenteImportiCapitoloStatoTipoComponenteImportiCapitoloModelDetail(TipoComponenteImportiCapitoloStatoTipoComponenteImportiCapitoloConverter.class, TipoComponenteImportiCapitoloModelDetail.StatoTipoComponenteImportiCapitolo),
	TipoComponenteImportiCapitoloCollegatoACapitoliModelDetail(TipoComponenteImportiCapitoloCollegatoACapitoliConverter.class, TipoComponenteImportiCapitoloModelDetail.CollegatoACapitoli),
	
	DettaglioVariazioneComponenteImportoCapitoloFlagModelDetail(DettaglioVariazioneComponenteImportoCapitoloFlagConverter.class, DettaglioVariazioneComponenteImportoCapitoloModelDetail.Flag),
	DettaglioVariazioneComponenteImportoCapitoloComponenteImportiCapitoloModelDetail(DettaglioVariazioneComponenteImportoCapitoloComponenteImportiCapitoloConverter.class, DettaglioVariazioneComponenteImportoCapitoloModelDetail.ComponenteImportiCapitolo),
	DettaglioVariazioneComponenteImportoCapitoloDettaglioVariazioneImportiCapitoloModelDetail(DettaglioVariazioneComponenteImportoCapitoloDettaglioVariazioneImportiCapitoloConverter.class, DettaglioVariazioneComponenteImportoCapitoloModelDetail.DettaglioVariazioneImportiCapitolo),
	;
	
	
	private final Class<? extends CustomConverter> converterClass;
	private final ModelDetail modelDetail;
	
	private  Converters(Class<? extends CustomConverter> converterClass, ModelDetail modelDetail){
		this.converterClass = converterClass;
		this.modelDetail = modelDetail;
	}
	
	

	@Override
	public Class<? extends CustomConverter> getCustomConverterClass() {
		return converterClass;
	}

	/**
	 * @return the allegatoAttoModelDetail
	 */
	public ModelDetail getModelDetail() {
		return modelDetail;
	}
	
	
	public static Converters byModelDetail(ModelDetail modelDetail){
		for(Converters e : Converters.values()){
			if(e.getModelDetail().equals(modelDetail)){
				return e;
			}
		}
		
		throw new IllegalStateException("Impossibile trovare un enum Converters con modelDetail: "+modelDetail);
		
	}
	
	/**
	 * Restituisce l'elenco dei Converter associati ai modelDetails passati come parametro.
	 * L'elenco restituito viene pulito dai duplicati ed ordinato in base all'ordine di dichiarazione dei field nell'Enum.
	 * 
	 * @param modelDetails
	 * @return elenco dei Converters
	 */
	public static Converters[] byModelDetails(ModelDetail... modelDetails) {
		Set<Converters> enums = EnumSet.noneOf(Converters.class);
		
		if(modelDetails!=null){
			for(ModelDetail modelDetail: modelDetails){
				enums.add(byModelDetail(modelDetail));
			}
		}
		
		return enums.toArray(new Converters[enums.size()]);
		
	}
	
	/**
	 * Ottiene il GeneriType A di un CustomConverter
	 * 
	 * @param customConverter
	 * @return
	 */
	public Class<?> getAType() {
		try {
			return Utility.findGenericType(converterClass, DozerConverter.class, 0);
		} catch(IllegalArgumentException iae) {
			// Errore nella derivazione del tipo generico: ignoro
			return null;
		}
	}


	/**
	 * Ottiene il GeneriType B di un CustomConverter
	 * 
	 * @param customConverter
	 * @return
	 */
	public Class<?> getBType() {
		try {
			return Utility.findGenericType(converterClass, DozerConverter.class, 1);
		} catch(IllegalArgumentException iae) {
			// Errore nella derivazione del tipo generico: ignoro
			return null;
		}
	}


}
