/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.siac.siacbilser.test.business.capitoloentrata;

import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;

import it.csi.siac.siacbilser.business.service.capitoloentrataprevisione.AggiornamentoMassivoCapitoloEntrataPrevisioneService;
import it.csi.siac.siacbilser.frontend.webservice.msg.AggiornaMassivoCapitoloDiEntrataPrevisione;
import it.csi.siac.siacbilser.frontend.webservice.msg.AggiornaMassivoCapitoloDiEntrataPrevisioneResponse;
import it.csi.siac.siacbilser.test.BaseJunit4TestCase;
import it.csi.siac.siaccommon.util.JAXBUtility;

/**
 * The Class GestioneCapitoloEntrataPrevisioneTest.
 */
public class GestioneCapitoloEntrataPrevisioneTest extends BaseJunit4TestCase {
	
	@Autowired
	private AggiornamentoMassivoCapitoloEntrataPrevisioneService aggiornamentoMassivoCapitoloEntrataPrevisioneService;
	
	@Test
	public void aggiornamentoMassivoCapitoloEntrataPrevisioneService() {
		StringBuilder sb = new StringBuilder();
		sb.append("<aggiornaMassivoCapitoloDiEntrataPrevisione>");
		sb.append("    <dataOra>2015-09-30T16:45:59.397+02:00</dataOra>");
		sb.append("    <richiedente>");
		sb.append("        <account>");
		sb.append("            <stato>VALIDO</stato>");
		sb.append("            <uid>1</uid>");
		sb.append("            <nome>Demo 21</nome>");
		sb.append("            <descrizione>Demo 21 - Città di Torino</descrizione>");
		sb.append("            <indirizzoMail>email</indirizzoMail>");
		sb.append("            <ente>");
		sb.append("                <stato>VALIDO</stato>");
		sb.append("                <uid>1</uid>");
		sb.append("                <gestioneLivelli>");
		sb.append("                    <entry>");
		sb.append("                        <key>LIVELLO_GESTIONE_BILANCIO</key>");
		sb.append("                        <value>GESTIONE_UEB</value>");
		sb.append("                    </entry>");
		sb.append("                </gestioneLivelli>");
		sb.append("                <nome>Città di Torino</nome>");
		sb.append("            </ente>");
		sb.append("        </account>");
		sb.append("        <operatore>");
		sb.append("            <stato>VALIDO</stato>");
		sb.append("            <uid>0</uid>");
		sb.append("            <codiceFiscale>AAAAAA00A11B000J</codiceFiscale>");
		sb.append("            <cognome>AAAAAA00A11B000J</cognome>");
		sb.append("            <nome>Demo</nome>");
		sb.append("        </operatore>");
		sb.append("    </richiedente>");
		sb.append("    <capitoloEntrataPrevisione>");
		sb.append("        <stato>VALIDO</stato>");
		sb.append("        <uid>0</uid>");
		sb.append("        <annoCapitolo>2015</annoCapitolo>");
		sb.append("        <bilancio>");
		sb.append("            <stato>VALIDO</stato>");
		sb.append("            <uid>16</uid>");
		sb.append("            <anno>2015</anno>");
		sb.append("        </bilancio>");
		sb.append("        <categoriaCapitolo>");
		sb.append("            <stato>VALIDO</stato>");
		sb.append("            <uid>2</uid>");
		sb.append("        </categoriaCapitolo>");
		sb.append("        <classificatoriGenerici>");
		sb.append("            <loginOperazione>migr_capitoli_p</loginOperazione>");
		sb.append("            <stato>VALIDO</stato>");
		sb.append("            <uid>454051</uid>");
		sb.append("            <codice>41</codice>");
		sb.append("            <descrizione>CIRCOSCRIZIONI COMUNALI</descrizione>");
		sb.append("            <tipoClassificatore>");
		sb.append("                <stato>VALIDO</stato>");
		sb.append("                <uid>0</uid>");
		sb.append("                <codice>CLASSIFICATORE_36</codice>");
		sb.append("                <descrizione>Allegati bilancio di previsione</descrizione>");
		sb.append("            </tipoClassificatore>");
		sb.append("        </classificatoriGenerici>");
		sb.append("        <classificatoriGenerici xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:nil=\"true\"/>");
		sb.append("        <classificatoriGenerici xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:nil=\"true\"/>");
		sb.append("        <classificatoriGenerici>");
		sb.append("            <loginOperazione>migr_capitoli_p</loginOperazione>");
		sb.append("            <stato>VALIDO</stato>");
		sb.append("            <uid>454158</uid>");
		sb.append("            <codice>130</codice>");
		sb.append("            <descrizione>ORGANIZZAZIONE</descrizione>");
		sb.append("            <tipoClassificatore>");
		sb.append("                <stato>VALIDO</stato>");
		sb.append("                <uid>0</uid>");
		sb.append("                <codice>CLASSIFICATORE_39</codice>");
		sb.append("                <descrizione>Aree</descrizione>");
		sb.append("            </tipoClassificatore>");
		sb.append("        </classificatoriGenerici>");
		sb.append("        <classificatoriGenerici>");
		sb.append("            <loginOperazione>migr_capitoli_p</loginOperazione>");
		sb.append("            <stato>VALIDO</stato>");
		sb.append("            <uid>453932</uid>");
		sb.append("            <codice>12</codice>");
		sb.append("            <descrizione>BILANCIO-TRIBUTI-PERSONALE-PATRIMONIO-DECENTRAM.TO GIANGUIDO PASSONI</descrizione>");
		sb.append("            <tipoClassificatore>");
		sb.append("                <stato>VALIDO</stato>");
		sb.append("                <uid>0</uid>");
		sb.append("                <codice>CLASSIFICATORE_40</codice>");
		sb.append("                <descrizione>Assessorati</descrizione>");
		sb.append("            </tipoClassificatore>");
		sb.append("        </classificatoriGenerici>");
		sb.append("        <classificatoriGenerici>");
		sb.append("            <loginOperazione>migr_capitoli_p</loginOperazione>");
		sb.append("            <stato>VALIDO</stato>");
		sb.append("            <uid>453850</uid>");
		sb.append("            <codice>0000</codice>");
		sb.append("            <descrizione> </descrizione>");
		sb.append("            <tipoClassificatore>");
		sb.append("                <stato>VALIDO</stato>");
		sb.append("                <uid>0</uid>");
		sb.append("                <codice>CLASSIFICATORE_41</codice>");
		sb.append("                <descrizione>Coel</descrizione>");
		sb.append("            </tipoClassificatore>");
		sb.append("        </classificatoriGenerici>");
		sb.append("        <classificatoriGenerici xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:nil=\"true\"/>");
		sb.append("        <classificatoriGenerici xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:nil=\"true\"/>");
		sb.append("        <classificatoriGenerici xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:nil=\"true\"/>");
		sb.append("        <classificatoriGenerici xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:nil=\"true\"/>");
		sb.append("        <classificatoriGenerici xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:nil=\"true\"/>");
		sb.append("        <classificatoriGenerici xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:nil=\"true\"/>");
		sb.append("        <classificatoriGenerici xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:nil=\"true\"/>");
		sb.append("        <classificatoriGenerici xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:nil=\"true\"/>");
		sb.append("        <classificatoriGenerici xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:nil=\"true\"/>");
		sb.append("        <descrizione>UNIONE EUROPEA - CONTRIBUTI</descrizione>");
		sb.append("        <descrizioneArticolo>CONTRIBUTI PER PROGETTO INNOCAT - VEDANSI CAPP. 45700/1 - 45800/25/26/27 SPESA</descrizioneArticolo>");
		sb.append("        <ente>");
		sb.append("            <stato>VALIDO</stato>");
		sb.append("            <uid>1</uid>");
		sb.append("            <gestioneLivelli>");
		sb.append("                <entry>");
		sb.append("                    <key>LIVELLO_GESTIONE_BILANCIO</key>");
		sb.append("                    <value>GESTIONE_UEB</value>");
		sb.append("                </entry>");
		sb.append("            </gestioneLivelli>");
		sb.append("            <nome>Città di Torino</nome>");
		sb.append("        </ente>");
		sb.append("        <flagImpegnabile>true</flagImpegnabile>");
		sb.append("        <flagRilevanteIva>false</flagRilevanteIva>");
		sb.append("        <note></note>");
		sb.append("        <numeroArticolo>18</numeroArticolo>");
		sb.append("        <numeroCapitolo>12500</numeroCapitolo>");
		sb.append("        <strutturaAmministrativoContabile>");
		sb.append("            <loginOperazione>admin</loginOperazione>");
		sb.append("            <stato>VALIDO</stato>");
		sb.append("            <uid>347</uid>");
		sb.append("            <codice>006</codice>");
		sb.append("            <descrizione>MOBILITA'</descrizione>");
		sb.append("            <livello>2</livello>");
		sb.append("            <tipoClassificatore>");
		sb.append("                <stato>VALIDO</stato>");
		sb.append("                <uid>0</uid>");
		sb.append("                <codice>CDC</codice>");
		sb.append("                <descrizione>Cdc(Settore)</descrizione>");
		sb.append("            </tipoClassificatore>");
		sb.append("        </strutturaAmministrativoContabile>");
		sb.append("        <statoOperativoElementoDiBilancio>VALIDO</statoOperativoElementoDiBilancio>");
		sb.append("        <tipoCapitolo>CAPITOLO_ENTRATA_PREVISIONE</tipoCapitolo>");
		sb.append("        <tipoFinanziamento>");
		sb.append("            <loginOperazione>migr_capitoli_p</loginOperazione>");
		sb.append("            <stato>VALIDO</stato>");
		sb.append("            <uid>453445</uid>");
		sb.append("            <codice>MB</codice>");
		sb.append("            <descrizione>MEZZI DI BILANCIO</descrizione>");
		sb.append("            <tipoClassificatore>");
		sb.append("                <stato>VALIDO</stato>");
		sb.append("                <uid>0</uid>");
		sb.append("                <codice>TIPO_FINANZIAMENTO</codice>");
		sb.append("                <descrizione>Tipo Finanziamento</descrizione>");
		sb.append("            </tipoClassificatore>");
		sb.append("        </tipoFinanziamento>");
		sb.append("        <uidCapitoloEquivalente>0</uidCapitoloEquivalente>");
		sb.append("        <uidExCapitolo>0</uidExCapitolo>");
		sb.append("        <categoriaTipologiaTitolo>");
		sb.append("            <loginOperazione>pentaho_TTC_20141113_1</loginOperazione>");
		sb.append("            <stato>VALIDO</stato>");
		sb.append("            <uid>119463</uid>");
		sb.append("            <codice>1010405</codice>");
		sb.append("            <descrizione>Compartecipazione IVA ai Comuni</descrizione>");
		sb.append("            <livello>3</livello>");
		sb.append("            <tipoClassificatore>");
		sb.append("                <stato>VALIDO</stato>");
		sb.append("                <uid>0</uid>");
		sb.append("                <codice>CATEGORIA</codice>");
		sb.append("                <descrizione>Categoria</descrizione>");
		sb.append("            </tipoClassificatore>");
		sb.append("        </categoriaTipologiaTitolo>");
		sb.append("        <flagPerMemoria>false</flagPerMemoria>");
		sb.append("        <tipologiaTitolo>");
		sb.append("            <loginOperazione>pentaho_TTC_20141113_1</loginOperazione>");
		sb.append("            <stato>VALIDO</stato>");
		sb.append("            <uid>119462</uid>");
		sb.append("            <codice>1010400</codice>");
		sb.append("            <descrizione>Tipologia 104: Compartecipazioni di tributi</descrizione>");
		sb.append("            <livello>2</livello>");
		sb.append("            <tipoClassificatore>");
		sb.append("                <stato>VALIDO</stato>");
		sb.append("                <uid>0</uid>");
		sb.append("                <codice>TIPOLOGIA</codice>");
		sb.append("                <descrizione>Tipologia</descrizione>");
		sb.append("            </tipoClassificatore>");
		sb.append("            <tipologiaFoglia>false</tipologiaFoglia>");
		sb.append("        </tipologiaTitolo>");
		sb.append("        <titoloEntrata>");
		sb.append("            <loginOperazione>pentaho_TTC_20141113_1</loginOperazione>");
		sb.append("            <stato>VALIDO</stato>");
		sb.append("            <uid>119434</uid>");
		sb.append("            <codice>1</codice>");
		sb.append("            <descrizione>ENTRATE CORRENTI DI NATURA TRIBUTARIA, CONTRIBUTIVA E PEREQUATIVA (2015)</descrizione>");
		sb.append("            <livello>1</livello>");
		sb.append("            <tipoClassificatore>");
		sb.append("                <stato>VALIDO</stato>");
		sb.append("                <uid>0</uid>");
		sb.append("                <codice>TITOLO_ENTRATA</codice>");
		sb.append("                <descrizione>Titolo Entrata</descrizione>");
		sb.append("            </tipoClassificatore>");
		sb.append("        </titoloEntrata>");
		sb.append("    </capitoloEntrataPrevisione>");
		sb.append("</aggiornaMassivoCapitoloDiEntrataPrevisione>");
		
		AggiornaMassivoCapitoloDiEntrataPrevisione req = JAXBUtility.unmarshall(sb.toString(), AggiornaMassivoCapitoloDiEntrataPrevisione.class);
		AggiornaMassivoCapitoloDiEntrataPrevisioneResponse res = aggiornamentoMassivoCapitoloEntrataPrevisioneService.executeService(req);
		assertNotNull(res);
	}
}
