/*
*SPDX-FileCopyrightText: Copyright 2020 | CSI Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.siac.siacfinser.business.service.enumeration;



/**
 * Descrive il mapping dell codifiche.
 * 
 * @author Valentina
 */
public enum CodiceEventoEnum {

	INSERISCI_IMPEGNO("IMP-INS"),
	INSERISCI_IMPEGNO_PRG("IMP-PRG"),
	INSERISCI_MODIFICA_IMPORTO_IMPEGNO("MIM-INS-I"), 
	ANNULLA_MODIFICA_IMPORTO_IMPEGNO("MIM-ANN"), 
	INSERISCI_MODIFICA_SOGGETTO_IMPEGNO("MIM-INS-S"), 
	INSERISCI_MODIFICA_IMPORTO_SUBIMPEGNO("MSI-INS-I"), 
	ANNULLA_MODIFICA_IMPORTO_SUBIMPEGNO("MSI-ANN-I"), 
	INSERISCI_MODIFICA_SOGGETTO_SUBIMPEGNO("MSI-INS-S"),
	INSERISCI_SUBIMPEGNO("SIM-INS"), 
	ANNULLA_SUBIMPEGNO("SIM-ANN"),
	// Nuove causali modifiche impegno in fase di bilancio ROR
	INSERISCI_MODIFICA_IMPORTO_IMPEGNO_ROR_COMPETENZA_MENO("ROR-I-COMP-INS"), // vecchia causale ROR-I-CM-INS
	INSERISCI_MODIFICA_IMPORTO_IMPEGNO_ROR_COMPETENZA_PIU("ROR-I-COMP-INS"), // vecchia causale ROR-I-CP-INS
	INSERISCI_MODIFICA_IMPORTO_SUBIMPEGNO_ROR_COMPETENZA_MENO("ROR-SI-COMP-INS"),//vecchia causale ROR-SI-CM-INS
	INSERISCI_MODIFICA_IMPORTO_SUBIMPEGNO_ROR_COMPETENZA_PIU("ROR-SI-COMP-INS"),//vecchia causale ROR-SI-CP-INS
	INSERISCI_MODIFICA_IMPORTO_IMPEGNO_ROR_RESIDUO_MENO("ROR-I-RM-INS"),
	INSERISCI_MODIFICA_IMPORTO_IMPEGNO_ROR_RESIDUO_PIU("ROR-I-RP-INS"),
	INSERISCI_MODIFICA_IMPORTO_SUBIMPEGNO_ROR_RESIDUO_MENO("ROR-SI-RM-INS"),
	INSERISCI_MODIFICA_IMPORTO_SUBIMPEGNO_ROR_RESIDUO_PIU("ROR-SI-RP-INS"),
	// Nuove causali modifiche accertamento in fase di bilancio ROR
	INSERISCI_MODIFICA_IMPORTO_ACCERTAMENTO_ROR_COMPETENZA_MENO("ROR-A-COMP-INS"), // vecchia causale ROR-A-CM-INS
	INSERISCI_MODIFICA_IMPORTO_ACCERTAMENTO_ROR_COMPETENZA_PIU("ROR-A-COMP-INS"), // vecchia causale ROR-A-CP-INS
	INSERISCI_MODIFICA_IMPORTO_SUBACCERTAMENTO_ROR_COMPETENZA_MENO("ROR-SA-COMP-INS"),// vecchia causale ROR-SA-CM-INS
	INSERISCI_MODIFICA_IMPORTO_SUBACCERTAMENTO_ROR_COMPETENZA_PIU("ROR-SA-COMP-INS"), //vecchia causale ROR-SA-CP-INS
	INSERISCI_MODIFICA_IMPORTO_ACCERTAMENTO_ROR_RESIDUO_MENO("ROR-A-RM-INS"),
	INSERISCI_MODIFICA_IMPORTO_ACCERTAMENTO_ROR_RESIDUO_PIU("ROR-A-RP-INS"),
	INSERISCI_MODIFICA_IMPORTO_SUBACCERTAMENTO_ROR_RESIDUO_MENO("ROR-SA-RM-INS"),
	INSERISCI_MODIFICA_IMPORTO_SUBACCERTAMENTO_ROR_RESIDUO_PIU("ROR-SA-RP-INS"),
	
	INSERISCI_ACCERTAMENTO("ACC-INS"),
	INSERISCI_MODIFICA_IMPORTO_ACCERTAMENTO("MAC-INS-I"), 
	ANNULLA_MODIFICA_IMPORTO_ACCERTAMENTO("MAC-ANN"), 
	INSERISCI_MODIFICA_SOGGETTO_ACCERTAMENTO("MAC-INS-S"),
	INSERISCI_MODIFICA_IMPORTO_SUBACCERTAMENTO("MSA-INS-I"),
	ANNULLA_MODIFICA_IMPORTO_SUBACCERTAMENTO("MSA-ANN-I"), 
	INSERISCI_MODIFICA_SOGGETTO_SUBACCERTAMENTO("MSA-INS-S"), 
	INSERISCI_SUBACCERTAMENTO("SAC-INS"), 
	ANNULLA_SUBACCERTAMENTO("SAC-ANN"), 
	
	INSERISCI_LIQUIDAZIONE("LIQ-INS"), 
	ANNULLA_LIQUIDAZIONE("LIQ-ANN"), 
	INSERISCI_LIQUIDAZIONE_CON_IMPEGNO_RESIDUO("LIQ-RES-INS"),
	AGGIORNA_LIQUIDAZIONE_CON_IMPEGNO_RESIDUO("LIQ-RES-AGG"), 
	ANNULLA_LIQUIDAZIONE_CON_IMPEGNO_RESIDUO("LIQ-RES-ANN"),
		
	INSERISCI_ORDINATIVO_PAGAMENTO("OPA-INS"), 
	AGGIORNA_ORDINATIVO_PAGAMENTO("OPA-AGG"), 
	ANNULLA_ORDINATIVO_PAGAMENTO("OPA-ANN"),
	
	INSERISCI_ORDINATIVO_PAGAMENTO_CEC("ORD-CEC-INS"), 
	AGGIORNA_ORDINATIVO_PAGAMENTO_CEC("ORD-CEC-AGG"), 
	ANNULLA_ORDINATIVO_PAGAMENTO_CEC("ORD-CEC-ANN"),
	

	INSERISCI_ORDINATIVO_INCASSO("OIN-INS"), 
	AGGIORNA_ORDINATIVO_INCASSO("OIN-AGG"), 
	ANNULLA_ORDINATIVO_INCASSO("OIN-ANN"),
	
	INSERISCI_ORDINATIVO_PAGAMENTO_SANITA("OPA-SAN-INS"),
	AGGIORNA_ORDINATIVO_PAGAMENTO_SANITA("OPA-SAN-AGG"),
	ANNULLA_ORDINATIVO_PAGAMENTO_SANITA("OPA-SAN-ANN"),
	
	INSERISCI_ORDINATIVO_INCASSO_SANITA("OIN-SAN-INS"),
	AGGIORNA_ORDINATIVO_INCASSO_SANITA("OIN-SAN-AGG"),
	ANNULLA_ORDINATIVO_INCASSO_SANITA("OIN-SAN-ANN")
	
	;

	private String codice;

	private CodiceEventoEnum(String codice) {

		setCodice(codice);

	}

	public static CodiceEventoEnum byCodice(String codice) {
		for (CodiceEventoEnum ce : CodiceEventoEnum
				.values()) {
			if (ce.getCodice().equals(codice)) {
				return ce;
			}
		}
		throw new IllegalArgumentException(
				"Impossibile trovare un mapping per il codice: " + codice
						+ " in CodiciControlloInnestiFinGenEnum");
	}

	/**
	 * @return the codice
	 */
	public String getCodice() {
		return codice;
	}

	/**
	 * @param collegamentoTipoCode
	 *            the collegamentoTipoCode to set
	 */
	public void setCodice(String codice) {
		this.codice = codice;
	}

}
